# -*- coding: utf-8 -*-
"""
Created on Thu Feb 11 10:58:32 2021

@author: jasak

to je datoteka za animacijo od vektorjev

"""

from manimlib.imports import *
import math
import numpy as np

# To watch one of these scenes, run the following:
# python -m manim example_scenes.py SquareToCircle -pl
#
# Use the flat -l for a faster rendering at a lower
# quality.
# Use -s to skip to the end and just save the final frame
# Use the -p to have the animation (or image, if -s was
# used) pop up once done.
# Use -n <number> to skip ahead to the n'th animation of a scene.
# Use -r <number> to specify a resolution (for example, -r 1080
# for a 1920x1080 video)

"""
Vektorji so matematične količine, ki imajo določeno dolžino, smer in orientacijo. 
Ponazarjamo jih z usmerjenimi daljicami. Ena ključnih lastnosti vektorjev je, da jih lahko prosto premikamo po  ru. 
Vsi vektorji, ki so enako dolgi, so vzporedni in so enako orientirani, so enaki. 
Poseben primer je vektor nič, ki ima dolžino 0. To je edini vektor, ki nima orientacije.

"""
class Osnove(Scene):
    def construct(self):
        title = TextMobject("Vektorji").scale(3)
        self.play(FadeIn(title))
        self.play(FadeOut(title))
        
        v = Line()
        self.play(FadeIn(v))
        self.play(ApplyMethod(v.scale,2))
        self.play(ApplyMethod(v.rotate, math.pi/5))
        v2 = Arrow(color="white").scale(2*1.34).rotate(math.pi/5)
        v3 = Arrow(color="white").scale(2*1.34).rotate(math.pi/5)
        v4 = Arrow(color="white").scale(2*1.34).rotate(math.pi/5)
        a1 = TexMobject("\\vec{a}").shift(0.5*LEFT + 0.5*UP)
        a2 = TexMobject("\\vec{a}").shift(0.5*LEFT + 0.5*UP)
        a3 = TexMobject("\\vec{a}").shift(0.5*LEFT + 0.5*UP)
        
        v2 = VGroup(v2, a1)
        v3 = VGroup(v3, a2)
        v4 = VGroup(v4, a3).shift(3*RIGHT+1*DOWN)
        self.play(ShowCreation(v2))
        #self.play(Write(a))
        self.wait(1)
        self.remove(v)
        self.play(ApplyMethod(v2.shift,np.array([-3,-1,0])))
        self.wait(1)
        self.play(ApplyMethod(v2.shift,np.array([6,3,0])))
        self.wait(1)
        self.play(ApplyMethod(v2.shift,np.array([0,-4,0])))
        self.wait(1)
        self.play(ApplyMethod(v2.shift,np.array([-6,3,0])))
        self.wait(1)
        self.play(FadeIn(v3))
        self.wait(1)
        self.play(FadeIn(v4))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        nicelni_vektor = Dot()
        nic = TexMobject("\\vec{0}").shift(0.5*UP)
        self.play(FadeIn(nicelni_vektor))
        self.play(FadeIn(nic))
        self.wait(1)
        self.play(FadeOut(nic), FadeOut(nicelni_vektor))
        #zdaj pride seštevanje vektorjev
        sestevanje = TextMobject("Seštevanje vektorjev").scale(2.5)
        self.play(FadeIn(sestevanje))
        self.wait(2)
        self.play(FadeOut(sestevanje))
        
        vek_a = Arrow(color='#58C4DD').shift(2*LEFT).scale(2)
        vek_b = Arrow(color='#FC6255').rotate(math.pi/3).shift(UP + 2*RIGHT).scale(2)
        crka_a = TexMobject("\\vec{a}").set_color(BLUE).move_to(vek_a).shift(0.5*DOWN)
        crka_b = TexMobject("\\vec{b}").set_color(RED).move_to(vek_b).shift(0.25*DOWN+0.5*RIGHT)
        v_a = VGroup(vek_a, crka_a).shift(0.75*DOWN)
        v_b = VGroup(vek_b, crka_b).shift(0.5*RIGHT)
        self.play(ShowCreation(v_a))
        self.play(ShowCreation(v_b))
        self.play(ApplyMethod(v_b.move_to, vek_a.get_end() + 1.5*0.866*UP + 1.5*0.5*RIGHT)) #ne vem, zakaj je *1.5
        self.wait(1)
        vek_ab = Arrow(start = vek_a.get_start(), end = vek_b.get_end()).set_color(PURPLE).scale(1.1)
        self.play(ShowCreation(vek_ab))
        crka_ab = TexMobject("\\vec{a} + \\vec{b}").move_to(vek_ab).shift(0.5*UP + 0.5*LEFT).set_color(PURPLE)
        self.play(Write(crka_ab, rate=2))
        self.wait(1)
        skoraj_vsi_ab = VGroup(v_a, v_b)
        
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        vsi_ab = VGroup(v_a, v_b, vek_ab, crka_ab).shift(2*LEFT)
        vek_a = Arrow(color='#58C4DD').shift(2*LEFT).scale(2)
        vek_b = Arrow(color='#FC6255').rotate(math.pi/3).shift(UP + 2*RIGHT).scale(2)
        crka_a = TexMobject("\\vec{a}").set_color(BLUE).move_to(vek_a).shift(-0.5*DOWN)
        crka_b = TexMobject("\\vec{b}").set_color(RED).move_to(vek_b).shift(-0.25*DOWN-0.5*RIGHT)
        v_a = VGroup(vek_a, crka_a).shift(0.75*DOWN)
        v_b = VGroup(vek_b, crka_b).shift(0.5*RIGHT)
        self.play(ShowCreation(v_a))
        self.play(ShowCreation(v_b))
        self.play(ApplyMethod(v_b.move_to, vek_a.get_start()+ 1.5*0.866*UP + 1.5*0.5*RIGHT))
        self.play(ApplyMethod(v_a.move_to, vek_b.get_end() + 0.2*UP +1.5*RIGHT))
        self.wait(1)
        vek_ba = Arrow(start = vek_b.get_start(), end = vek_a.get_end()).set_color(PURPLE).scale(1.1)
        self.play(ShowCreation(vek_ba))
        crka_ba = TexMobject("\\vec{b} + \\vec{a}").move_to(vek_ba).shift(-0.5*UP -0.5*LEFT).set_color(PURPLE)
        self.play(Write(crka_ba, rate=2))
        #vsi_ba = VGroup(v_a, v_b)
        self.wait(1)
        self.play(
            *[(ApplyMethod(mob.shift, 4*RIGHT)) for mob in self.mobjects]
        )
        self.play(FadeIn(vsi_ab))
        self.wait(1)
        self.play(FadeOut(v_a), FadeOut(v_b), FadeOut(skoraj_vsi_ab), ApplyMethod(vek_ba.rotate, math.pi/900))
        self.wait(1)
        ab = VGroup(vek_ab, crka_ab)
        ba = VGroup(vek_ba, crka_ba)
        self.play(ApplyMethod(ab.shift, 3*RIGHT+0.027*DOWN), ApplyMethod(ba.shift, 3*LEFT))
        self.wait(1)
        self.play(ApplyMethod(ab.shift, -3*RIGHT-0.027*DOWN), ApplyMethod(ba.shift, -3*LEFT))
        self.wait(0.5)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        #zdaj pride na vrsto sova, ter uvažanje svg slik
        sova =  ImageMobject("C:\\Users\\jasak\\manim\\manimlib\\mobject\\svg\\Sova.png")
        #self.play(FadeIn(sova))
        self.wait(1)
        vek_a1 = Arrow(color='#58C4DD').shift(2*LEFT).scale(2).rotate(-2*math.pi/5)
        vek_b1 = Arrow(color='#FC6255').scale(2).move_to(vek_a1.get_end() + 1.5*RIGHT)
        crka_a1 = TexMobject("\\vec{a}").set_color(BLUE).move_to(vek_a1).shift(0.5*0.92*LEFT + 0.5*0.39*DOWN)
        crka_b1 = TexMobject("\\vec{b}").set_color(RED).move_to(vek_b1).shift(0.5*DOWN)
        v_a1 = VGroup(vek_a1, crka_a1)
        v_b1 = VGroup(vek_b1, crka_b1)
        va1b1 = VGroup(v_a1, v_b1)
        vek_b2 = Arrow(color='#FC6255').scale(2).shift(2*UP)
        vek_a2 = Arrow(color='#58C4DD').rotate(-2*math.pi/5).scale(2).move_to(vek_b2.get_end() + 1.45*DOWN + 0.45*RIGHT)
        crka_a2 = TexMobject("\\vec{a}").set_color(BLUE).move_to(vek_a2).shift(-0.5*0.92*LEFT + -0.5*0.39*DOWN)
        crka_b2 = TexMobject("\\vec{b}").set_color(RED).move_to(vek_b2).shift(-0.5*DOWN)
        v_a2 = VGroup(vek_a2, crka_a2)
        v_b2 = VGroup(vek_b2, crka_b2)
        va2b2 = VGroup(v_a2, v_b2).shift(2*RIGHT)
        self.play(FadeIn(va1b1))
        sova.move_to(vek_a1.get_start() + 0.3*UP)
        self.play(FadeIn(sova))
        self.play(ApplyMethod(sova.move_to, vek_a1.get_end() + 0.3*UP), rate = 0.5)
        self.wait(1)
        self.play(ApplyMethod(sova.move_to, vek_b1.get_end() + 0.3*UP), rate = 0.5)
        self.wait(1)
        self.play(FadeOut(sova))
        sova.move_to(vek_a1.get_start() + 0.3*UP)
        vek_ab1 = Arrow(start = vek_a1.get_start(), end = vek_b1.get_end()).set_color(PURPLE).scale(1.1)
        self.play(ShowCreation(vek_ab1))
        crka_ab1 = TexMobject("\\vec{a} + \\vec{b}").move_to(vek_ab1).shift(0.5*UP + 0.7*RIGHT).set_color(PURPLE)
        self.play(Write(crka_ab1, rate = 2))
        self.play(FadeIn(sova))
        self.play(ApplyMethod(sova.move_to, vek_b1.get_end() + 0.3*UP), rate = 0.5)
        self.wait(1)
        #to spodaj ni več važno
        sova1 =  ImageMobject("C:\\Users\\jasak\\manim\\manimlib\\mobject\\svg\\Sova.png")
        self.play(
            *[(ApplyMethod(mob.shift, 2*LEFT)) for mob in self.mobjects]
        )
        self.play(FadeIn(va2b2))
        sova1.move_to(vek_b2.get_start() + 0.3*UP)
        self.play(FadeIn(sova1))
        self.play(ApplyMethod(sova1.move_to, vek_b2.get_end() + 0.3*UP), rate = 0.5)
        self.wait(1)
        self.play(ApplyMethod(sova1.move_to, vek_a2.get_end() + 0.3*UP), rate = 0.5)
        self.wait(1)
        self.play(FadeOut(sova1))
        vek_ba2 = Arrow(start = vek_b2.get_start(), end = vek_a2.get_end()).set_color(PURPLE).scale(1.1)
        self.play(ShowCreation(vek_ba2))
        crka_ba2 = TexMobject("\\vec{b} + \\vec{a}").move_to(vek_ba2).shift(-0.5*UP -  0.7*RIGHT).set_color(PURPLE)
        self.play(Write(crka_ba2, rate = 2))
        sova1.move_to(vek_b2.get_start() + 0.3*UP)
        self.play(FadeIn(sova1))
        self.play(ApplyMethod(sova1.move_to, vek_a2.get_end() + 0.3*UP), rate = 0.5)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        #tukaj pride del s seštevanjem
        
        
class SestevanjeInOdstevanje(Scene):
    def construct(self):
        v_beli_1 = Line(start = np.array([-4,-0.5,0]), end = np.array([-2, -0.5, 0])).add_tip()
        v_beli_2 = Line(start = np.array([-2,-0.5,0]), end = np.array([-1, -2, 0])).add_tip()
        v_beli_3 = Line(start = np.array([-1,-2,0]), end = np.array([2, -2, 0])).add_tip()
        v_beli_4 = Line(start = np.array([2,-2,0]), end = np.array([3, 2, 0])).add_tip()
        v_beli_5 = Line(start = np.array([3,2,0]), end = np.array([2.5, 3.5, 0])).add_tip()
        crka_beli_1 = TexMobject("\\vec{a}").move_to(v_beli_1.get_center() + 0.4*DOWN)
        crka_beli_2 = TexMobject("\\vec{b}").move_to(v_beli_2.get_center() + 0.2*DOWN + 0.35*LEFT)
        crka_beli_3 = TexMobject("\\vec{c}").move_to(v_beli_3.get_center() + 0.4*DOWN)
        crka_beli_4 = TexMobject("\\vec{d}").move_to(v_beli_4.get_center() + 0.15*DOWN + 0.4*RIGHT)
        crka_beli_5 = TexMobject("\\vec{e}").move_to(v_beli_5.get_center() + 0.4*RIGHT)
        
        beli_vektorji = VGroup(v_beli_1, v_beli_2, v_beli_3, v_beli_4, v_beli_5, crka_beli_1, crka_beli_2, crka_beli_3, crka_beli_4, crka_beli_5).shift(0.5*DOWN)
        self.play(FadeIn(beli_vektorji))
        self.wait(1)
        p_vijolicni_ab = Line(start = v_beli_1.get_start(), end = v_beli_2.get_end()).set_color(PURPLE).add_tip()
        crka_vijolicni_ab = TexMobject("\\vec{a} + \\vec{b}").set_color(PURPLE).shift(DOWN)
        v_vijolicni_ab = VGroup(p_vijolicni_ab, crka_vijolicni_ab)
        p_vijolicni_ac = Line(start = v_beli_1.get_start(), end = v_beli_3.get_end()).set_color(PURPLE).add_tip()
        crka_vijolicni_ac = TexMobject("\\vec{a} + \\vec{b} + \\vec{c}").set_color(PURPLE).shift(0.6*DOWN)
        v_vijolicni_ac = VGroup(p_vijolicni_ac, crka_vijolicni_ab)
        p_vijolicni_ad = Line(start = v_beli_1.get_start(), end = v_beli_4.get_end()).set_color(PURPLE).add_tip()
        crka_vijolicni_ad = TexMobject("\\vec{a} + \\vec{b} + \\vec{c} + \\vec{d}").set_color(PURPLE).shift(0.35*DOWN)
        p_vijolicni_ae = Line(start = v_beli_1.get_start(), end = v_beli_5.get_end()).set_color(PURPLE).add_tip()
        crka_vijolicni_ae = TexMobject("\\vec{a} + \\vec{b} + \\vec{c} + \\vec{d} + \\vec{e}").set_color(PURPLE)
        self.play(ShowCreation(p_vijolicni_ab), ShowCreation(crka_vijolicni_ab))
        self.wait(2)
        self.play(Transform(p_vijolicni_ab, p_vijolicni_ac), Transform(crka_vijolicni_ab, crka_vijolicni_ac))
        self.wait(2)
        self.play(Transform(p_vijolicni_ab, p_vijolicni_ad), Transform(crka_vijolicni_ab, crka_vijolicni_ad))
        self.wait(2)
        self.play(Transform(p_vijolicni_ab, p_vijolicni_ae), Transform(crka_vijolicni_ab, crka_vijolicni_ae))
        self.wait(2)
        p_vijolicni_bd = Line(start = v_beli_2.get_start(), end = v_beli_4.get_end()).set_color(PURPLE).add_tip()
        crka_vijolicni_bd = TexMobject("\\vec{b} + \\vec{c} + \\vec{d}").set_color(PURPLE).shift(0.75*LEFT + 0.5*UP)
        p_vijolicni_ce = Line(start = v_beli_3.get_start(), end = v_beli_5.get_end()).set_color(PURPLE).add_tip()
        crka_vijolicni_ce  = TexMobject("\\vec{c} + \\vec{d} + \\vec{e}").set_color(PURPLE).shift(0.5*LEFT + 0.5*UP)
        self.play(Transform(p_vijolicni_ab, p_vijolicni_bd), Transform(crka_vijolicni_ab, crka_vijolicni_bd))
        self.wait(2)
        self.play(Transform(p_vijolicni_ab, p_vijolicni_ce), Transform(crka_vijolicni_ab, crka_vijolicni_ce))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        odstevanje = TextMobject("Odštevanje vektorjev").scale(2.5  )
        self.play(FadeIn(odstevanje))
        self.wait(2)
        self.play(FadeOut(odstevanje))
        voa = Arrow().scale(2).set_color(BLUE).shift(2*LEFT).rotate(math.pi/4)
        vob = Arrow().scale(2).set_color(RED).shift(2*RIGHT).rotate(-math.pi/3)
        vnoa = Arrow().scale(2).set_color(BLUE).shift(2*LEFT).rotate(5*math.pi/4)
        vnob = Arrow().scale(2).set_color(RED).shift(2*RIGHT).rotate(2*math.pi/3)
        crka_voa = TexMobject("\\vec{a}").move_to(voa.get_center() + 2*DOWN).set_color(BLUE)
        crka_vob = TexMobject("\\vec{b}").move_to(vob.get_center() + 2*DOWN).set_color(RED)
        crka_nvoa = TexMobject("-\\vec{a}").move_to(voa.get_center() + 2*DOWN).set_color(BLUE)
        crka_nvob = TexMobject("-\\vec{b}").move_to(vob.get_center() + 2*DOWN).set_color(RED)
        vektorji_odstevanje = VGroup(voa, vob, crka_voa, crka_vob)
        self.play(FadeIn(vektorji_odstevanje))
        self.wait(1)
        self.play(Transform(crka_voa,crka_nvoa), Transform(voa, vnoa))
        self.wait(1)
        self.play(Transform(crka_vob,crka_nvob), Transform(vob, vnob))
        self.wait(1)
        """
        self.play(Transform(crka_voa,crka_voa), Transform(voa, voa))
        self.wait(1)
        self.play(Transform(crka_vob,crka_vob), Transform(vob, vob))
        """
        self.play(ApplyMethod(voa.rotate, math.pi), Transform(crka_voa, TexMobject("\\vec{a}").move_to(voa.get_center() + 2*DOWN).set_color(BLUE)))
        self.wait(1)
        self.play(ApplyMethod(vob.rotate, math.pi), Transform(crka_vob, TexMobject("\\vec{b}").move_to(vob.get_center() + 2*DOWN).set_color(RED)))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        nicelni_vektor = Dot()
        nic = TexMobject("\\vec{0}").shift(0.5*UP)
        minus = TexMobject("-").move_to(nic.get_center() + 0.4*LEFT + 0.05*DOWN)
        self.play(FadeIn(nicelni_vektor), FadeIn(nic))
        self.wait(1)
        self.play(FadeIn(minus))
        self.wait(1)
        self.play(FadeOut(minus))
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        vektorji_odstevanje.shift(0.5*DOWN)
        self.play(FadeIn(voa), FadeIn(vob), FadeIn(crka_voa), FadeIn(crka_vob))
        self.wait(1)
        vo1 = VGroup(voa, crka_voa)
        vo2 = VGroup(vob, crka_vob)
        self.play(ApplyMethod(vo2.move_to, 0.225*LEFT + 1.22*DOWN))
        vnob = Arrow().scale(2).rotate(2*math.pi/3).set_color(RED).move_to(1.7*LEFT + 1.8*UP)
        crka_nvob = TexMobject("-\\vec{b}").move_to(vob.get_center() + 2.5*UP + 0.5*LEFT).set_color(RED)
        
        
        self.wait(1)
        razlika = TexMobject("\\vec{a} - \\vec{b}").move_to(3*RIGHT + 2*UP)
        drugacen_zapis = TexMobject("\\vec{a} + \\left(-\\vec{b}\\right)").move_to(3*RIGHT + 1*UP)
        self.play(FadeIn(razlika))
        self.wait(1)
        self.play(TransformFromCopy(razlika, drugacen_zapis))
        self.wait(1)
        self.play(Transform(vob, vnob), Transform(crka_vob, crka_nvob))
        self.wait(1)
        vijolicni_aminusb = Arrow(start = voa.get_start(), end = vnob.get_end()).set_color(PURPLE).scale(1.1)
        crka_vijolicni_aminusb = TexMobject("\\vec{a} - \\vec{b}").move_to(vijolicni_aminusb.get_center() + 1*LEFT + 0.1*UP).set_color(PURPLE)
        self.play(ShowCreation(vijolicni_aminusb))
        self.play(Write(crka_vijolicni_aminusb, rate=2))
        self.wait(1)
        odstevanje_enacbi1 = VGroup(razlika, drugacen_zapis)
        drugacna_razlika = TexMobject("\\vec{b} - \\vec{a}").move_to(3*RIGHT + 1.4*UP)
        self.play(Transform(odstevanje_enacbi1, drugacna_razlika))
        desni_vektorji_o = VGroup(voa, vob, crka_voa, crka_vob)
        self.play(ApplyMethod(desni_vektorji_o.shift, 3.5*RIGHT), ApplyMethod(odstevanje_enacbi1.shift, 2*RIGHT))
        """
        vnoa = Arrow().scale(2).set_color(BLUE).shift(2*LEFT).rotate(5*math.pi/4)
        vnob = Arrow().scale(2).rotate(2*math.pi/3).set_color(RED).move_to(1.7*LEFT + 1.8*UP)
        """
        vijolicni_bminusa = Arrow(start = vijolicni_aminusb.get_end(), end = vijolicni_aminusb.get_start()).set_color(PURPLE).scale(1.125).shift(3.5*RIGHT)
        crka_vijolicni_bminusa = TexMobject("\\vec{b} - \\vec{a}").move_to(vijolicni_bminusa.get_center() + 1*LEFT + 0.1*UP).set_color(PURPLE)
        crka_voa2 = TexMobject("-\\vec{a}").move_to(voa.get_center() - 1.4*UP).set_color(BLUE)
        crka_vob2 = TexMobject("\\vec{b}").move_to(crka_nvob.get_center() + 3.5*RIGHT).set_color(RED)
        self.play(ApplyMethod(voa.rotate, math.pi), ApplyMethod(vob.rotate, math.pi), Transform(crka_vob, crka_vob2), Transform(crka_voa, crka_voa2))
        self.wait(1)
        self.play(ShowCreation(vijolicni_bminusa))
        self.play(Write(crka_vijolicni_bminusa, rate=2))
        self.wait(1)
        self.play(FadeOut(desni_vektorji_o), FadeOut(odstevanje_enacbi1))
        enakost1 = TexMobject("\\vec{a} - \\vec{b} \\neq \\vec{b} - \\vec{a}").move_to(3.75*RIGHT + 1.4*UP)
        enakost2 = TexMobject("\\vec{a} - \\vec{b} = -(\\vec{b} - \\vec{a})").move_to(3.75*RIGHT + 0.4*UP)
        self.play(Write(enakost1, rate=2))
        self.wait(1)
        self.play(Write(enakost2, rate=2))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        #množenje s skalarjem
        
        mnozenje_s_skalarjem = TextMobject("Množenje s skalarjem").scale(2.5)
        self.play(FadeIn(mnozenje_s_skalarjem))
        self.wait(2)
        self.play(FadeOut(mnozenje_s_skalarjem))
        
        
        
        a_mnoz = Arrow().rotate(math.pi/6)
        crka_a_mnoz = TexMobject("\\vec{a}").move_to(a_mnoz.get_center() + 0.5*DOWN + 0.3*RIGHT)
        kopija_a_mnoz = Arrow().shift(UP+LEFT).rotate(math.pi/6)
        kopija_crka_a_mnoz = TexMobject("\\vec{a}").move_to(kopija_a_mnoz.get_center() + 0.5*UP + 0.3*LEFT)
        skalar_n = TexMobject("n").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.075*DOWN).set_color(RED)
        skalar_2 = TexMobject("2").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.035*DOWN).set_color(RED)
        skalar_3 = TexMobject("3").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.035*DOWN).set_color(RED)
        skalar_koren_29 = TexMobject("\\sqrt{29}").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.025*DOWN).set_color(RED)
        skalar_pi = TexMobject("\\pi").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.055*DOWN).set_color(RED)
        self.play(ShowCreation(a_mnoz), ShowCreation(crka_a_mnoz))
        self.wait(0.5)
        self.play(Write(skalar_n, rate=2))
        self.wait(1)
        self.play(FadeIn(kopija_a_mnoz), FadeIn(kopija_crka_a_mnoz))
        self.play(Transform(skalar_n, skalar_2), ApplyMethod(a_mnoz.scale, 2))
        self.wait(1)
        self.play(Transform(skalar_n, skalar_3), ApplyMethod(a_mnoz.scale, 1.5))
        self.wait(1)
        self.play(Transform(skalar_n, skalar_koren_29), ApplyMethod(a_mnoz.scale, math.sqrt(29)/3), ApplyMethod(crka_a_mnoz.shift, 0.3*RIGHT))
        self.wait(1)
        self.play(Transform(skalar_n, skalar_pi), ApplyMethod(a_mnoz.scale, math.pi/math.sqrt(29)), ApplyMethod(crka_a_mnoz.shift, 0.3*LEFT))
        self.wait(1)
        
        #zdaj pridejo na vrsto negativna števila
        
        skalar_mpi = TexMobject("-\\pi").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.055*DOWN).set_color(RED)
        skalar_m1 = TexMobject("-").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.075*DOWN).set_color(RED)
        skalar_m5 = TexMobject("-5").move_to(crka_a_mnoz.get_center() + 0.3*LEFT + 0.035*DOWN).set_color(RED)
        self.play(Transform(skalar_n, skalar_mpi), ApplyMethod(a_mnoz.scale, -1), ApplyMethod(crka_a_mnoz.shift, 0.2*RIGHT))
        self.wait(1)
        self.play(Transform(skalar_n, skalar_m5), ApplyMethod(a_mnoz.scale, 5/math.pi))
        self.wait(1)
        self.play(Transform(skalar_n, skalar_m1), ApplyMethod(a_mnoz.scale, 1/5), ApplyMethod(crka_a_mnoz.shift, 0.15*LEFT))
        self.wait(1)
        skalar_05 = TexMobject("\\frac{1}{2}").move_to(crka_a_mnoz.get_center() + 0.1*LEFT + 0.235*DOWN).set_color(RED).scale(0.75)
        skalar_067 = TexMobject("0,67").move_to(crka_a_mnoz.get_center() + 0.1*RIGHT + 0.235*DOWN).set_color(RED)
        self.play(Transform(skalar_n, skalar_05), ApplyMethod(a_mnoz.scale, -1/2), ApplyMethod(crka_a_mnoz.shift, 0.25*RIGHT + 0.2*DOWN))
        self.wait(1)
        self.play(Transform(skalar_n, skalar_067), ApplyMethod(a_mnoz.scale, 2*0.67), ApplyMethod(crka_a_mnoz.shift, 0.55*RIGHT))
        self.wait(1)
        celo_ime = VGroup(skalar_n, crka_a_mnoz)
        nicelni_vektor = Dot()
        nic = TexMobject("\\vec{0}").shift(0.5*DOWN, 0.5*RIGHT)
        skalar_0 = TexMobject("0").move_to(crka_a_mnoz.get_center() + 0.7*LEFT + (-0.2+0.045)*DOWN).set_color(RED)
        self.play(Transform(skalar_n, skalar_0), Transform(a_mnoz, nicelni_vektor), ApplyMethod(crka_a_mnoz.shift, 0.2*UP + 0.4*LEFT))
        self.wait(1)
        self.play(Transform(celo_ime, nic), Transform(a_mnoz, nicelni_vektor))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        linearna_kombinacija = TextMobject("Linearna kombinacija").scale(2)
        self.play(FadeIn(linearna_kombinacija))
        self.wait(2)
        self.play(FadeOut(linearna_kombinacija))
        primer_lk1 = TexMobject("3","\\vec{a}").move_to(ORIGIN + 2*UP).scale(1.35).set_color_by_tex("{a}", RED).set_color_by_tex("{b}", BLUE)
        primer_lk2 = TexMobject("\\vec{a}"," - 2","\\vec{b}").scale(1.35).set_color_by_tex("{a}", RED).set_color_by_tex("{b}", BLUE)
        primer_lk3 = TexMobject("-\\frac{1}{2}","\\vec{a}","+\\frac{3}{4}","\\vec{b}","-\\frac{5}{3}","\\vec{c}").move_to(ORIGIN - 2*UP).scale(1.35).set_color_by_tex("{a}", RED).set_color_by_tex("{b}", BLUE).set_color_by_tex("{c}", GREEN)
        self.play(Write(primer_lk1, rate=2))
        self.wait(1)
        self.play(Write(primer_lk2, rate=2))
        self.wait(1)
        self.play(Write(primer_lk3, rate=2))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        vek_loa = Arrow().move_to(ORIGIN + 2*LEFT + 2*UP)
        vek_lob = Arrow().move_to(ORIGIN +2*LEFT + 2*DOWN).scale(2)
        vek_loc = Arrow().move_to(ORIGIN +2*RIGHT + 2*DOWN).scale(2.16).rotate(math.pi/4)
        vek_lod = Arrow().move_to(ORIGIN +2*RIGHT + 2*UP).scale(1.2).rotate(5*math.pi/4)
        crka_loa = TexMobject("\\vec{a}").move_to(vek_loa.get_center() + 0.5*DOWN)
        crka_lob = TexMobject("\\vec{b}").move_to(vek_lob.get_center() + 0.5*DOWN)
        crka_loc = TexMobject("\\vec{c}").move_to(vek_loc.get_center() + (0.5/math.sqrt(2))*DOWN + (0.5/math.sqrt(2))*RIGHT)
        crka_lod = TexMobject("\\vec{d}").move_to(vek_lod.get_center() + (0.5/math.sqrt(2))*UP + (0.5/math.sqrt(2))*LEFT)
        self.play(FadeIn(vek_loa), FadeIn(vek_lob), FadeIn(vek_loc), FadeIn(vek_lod))
        self.play(Write(crka_loa, rate=2))
        self.play(Write(crka_lob, rate=2))
        self.play(Write(crka_loc, rate=2))
        self.play(Write(crka_lod, rate=2))
        self.wait(1)
        self.play(ApplyMethod(vek_loa.set_color, "#44FF00"), ApplyMethod(vek_lob.set_color, "#44FF00"), ApplyMethod(crka_loa.set_color, "#44FF00"), ApplyMethod(crka_lob.set_color, "#44FF00"))
        self.wait(1)
        self.play(ApplyMethod(vek_loa.set_color, RED),ApplyMethod(vek_loc.set_color, RED), ApplyMethod(vek_lob.set_color, WHITE), ApplyMethod(crka_lob.set_color, WHITE), ApplyMethod(crka_loa.set_color, RED), ApplyMethod(crka_loc.set_color, RED))
        self.wait(1)
        self.play(ApplyMethod(vek_loc.set_color, "#44FF00"), ApplyMethod(crka_loc.set_color, "#44FF00"), ApplyMethod(vek_lod.set_color, "#44FF00"),ApplyMethod(crka_lod.set_color, "#44FF00"), ApplyMethod(vek_loa.set_color, WHITE), ApplyMethod(crka_loa.set_color, WHITE))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )

        natanko_tedaj = TexMobject("\\Leftrightarrow")
        linearno_odvisna = TextMobject("linearno odvisna").next_to(natanko_tedaj, direction = LEFT)
        lo_a = TexMobject("\\vec{a} =").next_to(natanko_tedaj)
        lo_n = TexMobject("n").next_to(lo_a).shift(0.08*DOWN)
        lo_n2 = TexMobject("n").next_to(lo_a).shift(0.08*DOWN).set_color(RED).shift(4*LEFT)
        lo_b = TexMobject("\\vec{b}").next_to(lo_n).shift(0.11*UP+0.2*LEFT)
        lo_b2 = TexMobject("\\vec{b}").next_to(lo_n2).shift(0.11*UP + -0.2*RIGHT)
        self.play(FadeIn(linearno_odvisna),FadeIn(natanko_tedaj),FadeIn(lo_a),FadeIn(lo_n),FadeIn(lo_b))
        self.wait(1)
        self.play(ApplyMethod(lo_n.set_color, RED))
        self.wait(1)
        rhs_1 = VGroup(lo_a, lo_n, lo_b)
        self.play(FadeOut(linearno_odvisna), FadeOut(natanko_tedaj), ApplyMethod(rhs_1.shift, 2*RIGHT))
        self.play(FadeIn(vek_loa), FadeIn(vek_lob))
        self.play(Write(crka_loa, rate=2))
        self.play(Write(crka_lob, rate=2))
        skalar_0_5 = TexMobject("0,5").set_color(RED).move_to(lo_n.get_center() + 0.03*UP + 0.1*RIGHT)
        self.play(Transform(lo_n, skalar_0_5), ApplyMethod(vek_lob.scale, 0.5), ApplyMethod(lo_b.shift, 0.3*RIGHT))
        self.wait(2)
        self.play(FadeOut(vek_loa), FadeOut(vek_lob), FadeOut(crka_loa), FadeOut(crka_lob), ApplyMethod(rhs_1.shift, 6*LEFT), Transform(lo_n, lo_n2), Transform(lo_b, lo_b2))
        self.wait(1)
        vek_loc.set_color(WHITE)
        vek_lod.set_color(WHITE)
        crka_loc.set_color(WHITE)
        crka_lod.set_color(WHITE)
        self.play(FadeIn(vek_loc), FadeIn(vek_lod))
        self.play(Write(crka_loc, rate=2))
        self.play(Write(crka_lod, rate=2))
        self.wait(1)
        lo_c = TexMobject("\\vec{c} =").move_to(lo_a.get_center())
        lo_d = TexMobject("\\vec{d}").move_to(lo_b.get_center() + 0.05*RIGHT + 0.03*UP)
        self.play(Transform(lo_a, lo_c),Transform(lo_b, lo_d))
        self.wait(1)
        skalar_18 = TexMobject("-1,8").set_color(RED).move_to(lo_n.get_center() + 0.03*UP + 0.2*RIGHT)
        self.play(Transform(lo_n, skalar_18), ApplyMethod(vek_lod.scale, -1.8), ApplyMethod(lo_b.shift, 0.6*RIGHT))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )

class LinearnaKombinacija(SpecialThreeDScene):
    def construct(self):
        #tukaj bo razložena ortonormirana baza
        
        plane = NumberPlane()
        self.play(ShowCreation(plane))
        vek_baz_a = Line(start=ORIGIN, end = ORIGIN + RIGHT).set_color(RED).add_tip()
        crka_baz_a = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a.get_center()+0.5*DOWN)
        v_b_a = VGroup(vek_baz_a, crka_baz_a)
        vek_baz_b = Line(start=ORIGIN, end = ORIGIN + UP).set_color(BLUE).add_tip()
        crka_baz_b = TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_baz_b.get_center()+0.5*LEFT)
        v_b_b = VGroup(vek_baz_b, crka_baz_b)
        vek_baz_c = Line(start=ORIGIN, end = ORIGIN + 3*RIGHT + 2*UP).add_tip()
        crka_baz_c = TexMobject("\\vec{c}").set_color(WHITE).move_to(vek_baz_c.get_center()+0.35*DOWN+0.35*RIGHT)
        v_b_c = VGroup(vek_baz_c, crka_baz_c)
        #self.play(ApplyMethod(plane.scale,1.5))
        self.play(ShowCreation(vek_baz_a))
        self.play(Write(crka_baz_a, rate=2))
        #plane.main_lines.fade(0.9)
        self.play(ShowCreation(vek_baz_b))
        self.play(Write(crka_baz_b, rate=2))
        self.wait(1)
        self.play(ShowCreation(vek_baz_c))
        self.play(Write(crka_baz_c, rate=2))
        self.wait(1)
        #rotacijska_matrika = [[1,1],[0,1]]
        #self.play(ApplyMethod(plane.apply_matrix, rotacijska_matrika))
        vek_baz_a2 = Line(start=ORIGIN, end = ORIGIN + RIGHT).set_color(RED).add_tip().shift(RIGHT)
        crka_baz_a2 = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a2.get_center()+0.5*DOWN)
        v_b_a2 = VGroup(vek_baz_a2, crka_baz_a2) 
        vek_baz_a3 = Line(start=ORIGIN, end = ORIGIN + RIGHT).set_color(RED).add_tip().shift(2*RIGHT)
        crka_baz_a3 = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a3.get_center()+0.5*DOWN)
        v_b_a3 = VGroup(vek_baz_a3, crka_baz_a3)
        vek_baz_a4 = Line(start=ORIGIN, end = ORIGIN + RIGHT).set_color(RED).add_tip().shift(3*RIGHT)
        crka_baz_a4 = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a4.get_center()+0.5*DOWN)
        v_b_a4 = VGroup(vek_baz_a4, crka_baz_a4)
        vek_baz_b2 = Line(start=ORIGIN, end = ORIGIN + UP).set_color(BLUE).add_tip().shift(UP)
        crka_baz_b2 = TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_baz_b2.get_center()+0.5*LEFT)
        v_b_b2 = VGroup(vek_baz_b2, crka_baz_b2)
        self.play(ShowCreation(v_b_a2), ShowCreation(v_b_a3))
        self.wait(1)
        self.play(ShowCreation(v_b_b2))
        self.wait(1)
        """
        vzporedna_crtasta = DashedLine(start = ORIGIN+2*UP, end=ORIGIN+2*UP+3*RIGHT)
        navpicna_crtasta = DashedLine(start=ORIGIN + 3*RIGHT, end=ORIGIN + 3*RIGHT + 2*UP)
        self.play(FadeIn(vzporedna_crtasta), FadeIn(navpicna_crtasta))
        self.wait(1)
        """
        self.play(ApplyMethod(v_b_b.shift, 3*RIGHT),ApplyMethod(v_b_b2.shift, 3*RIGHT), ApplyMethod(crka_baz_b.shift, 4*RIGHT),ApplyMethod(crka_baz_b2.shift, 4*RIGHT))
        self.wait(1)
        prva_stevilka = DecimalNumber(3, num_decimal_places = 1)
        druga_stevilka = DecimalNumber(2, num_decimal_places = 1, include_sign=True)
        enacba1_1 = TexMobject("\\vec{c} =")
        #lhs = VGroup(prva_stevilka, enacba1_1)
        #enacba1_2 = prva_stevilka
        enacba1_3 = TexMobject("\\vec{a}").set_color_by_tex("{a}", RED)
        enacba1_5 = TexMobject("\\vec{b}").set_color(BLUE)
        enacba1 = VGroup(enacba1_1, prva_stevilka, enacba1_3, druga_stevilka, enacba1_5)
        enacba1.arrange_submobjects(RIGHT, buff=SMALL_BUFF)
        enacba1.move_to(3*LEFT + 0.7*UP)
        enacba1_5.shift(0.05*UP)
        #enacba1 = TexMobject("\\vec{c} =", prva_stevilka,"\\vec{a} +", druga_stevilka ,"\\vec{b}")
        #enacba1.set_color_by_tex("{a}", RED).set_color_by_tex("{b}", BLUE).move_to(0.7*UP + 2.5*LEFT)
        self.play(TransformFromCopy(crka_baz_c, enacba1))
        self.wait(1)
        #self.play(ChangeDecimalToValue(prva_stevilka, 4))
        self.play(FadeOut(v_b_b2), FadeOut(v_b_a2), FadeOut(v_b_a3), ApplyMethod(vek_baz_b.shift, 3*LEFT), ApplyMethod(crka_baz_b.shift, 4*LEFT))
        vek_baz_d = Line(start=ORIGIN, end = ORIGIN + 4*RIGHT + 1*UP).add_tip()
        crka_baz_d = TexMobject("\\vec{c}").set_color(WHITE).move_to(vek_baz_d.get_center()+0.45*UP+0.15*LEFT)
        v_b_d = VGroup(vek_baz_d, crka_baz_d)
        self.play(Transform(v_b_c, v_b_d),ChangeDecimalToValue(prva_stevilka, 4), ChangeDecimalToValue(druga_stevilka, 1),run_time=2)
        self.wait(1)
        self.play(ShowCreation(v_b_a2),ShowCreation(v_b_a3), ShowCreation(v_b_a4))
        self.wait(1)
        self.play(ApplyMethod(crka_baz_b.shift, 5*RIGHT), ApplyMethod(vek_baz_b.shift, 4*RIGHT))
        self.wait(1)
        #enacba2 = TexMobject("\\vec{c} = 4","\\vec{a}", " + " ,"\\vec{b}")
        #enacba2.set_color_by_tex("{a}", RED).set_color_by_tex("{b}", BLUE).move_to(0.7*UP + 2.5*LEFT)
        #self.play(TransformFromCopy(crka_baz_c, enacba2))
        self.play(FadeOut(v_b_a2), FadeOut(v_b_a3), FadeOut(v_b_a4), ApplyMethod(vek_baz_b.shift, 4*LEFT), ApplyMethod(crka_baz_b.shift, 5*LEFT))
        self.wait(1)
        vek_baz_e = Line(start=ORIGIN, end = ORIGIN + 3*RIGHT - 3*UP).add_tip()
        crka_baz_e = TexMobject("\\vec{c}").set_color(WHITE).move_to(vek_baz_e.get_center()+0.35*UP+0.35*RIGHT)
        v_b_e = VGroup(vek_baz_e, crka_baz_e)
        self.play(Transform(v_b_c, v_b_e),ChangeDecimalToValue(prva_stevilka, 3), ChangeDecimalToValue(druga_stevilka, -3),run_time=2)
        self.wait(1)
        vek_baz_f = Line(start=ORIGIN, end = ORIGIN + 5*LEFT - 2*UP).add_tip()
        crka_baz_f = TexMobject("\\vec{c}").set_color(WHITE).move_to(vek_baz_f.get_center()+0.15*DOWN+0.45*RIGHT)
        v_b_f = VGroup(vek_baz_f, crka_baz_f)
        self.play(Transform(v_b_c, v_b_f),ApplyMethod(enacba1_1.shift, 0.35*LEFT),ApplyMethod(prva_stevilka.shift, 0.35*LEFT),ChangeDecimalToValue(prva_stevilka, -5), ChangeDecimalToValue(druga_stevilka, -2),run_time=2)
        self.wait(1)
        vek_baz_g = Line(start=ORIGIN, end = ORIGIN + 4*LEFT + 1*UP).add_tip()
        crka_baz_g = TexMobject("\\vec{c}").set_color(WHITE).move_to(vek_baz_g.get_center()+0.25*DOWN+0.45*LEFT)
        v_b_g = VGroup(vek_baz_g, crka_baz_g)
        self.play(Transform(v_b_c, v_b_g),ApplyMethod(enacba1.shift,1.5*UP), ChangeDecimalToValue(prva_stevilka, -4), ChangeDecimalToValue(druga_stevilka, 1),run_time=2)
        self.wait(1)
        """
        vek_baz_d = Line(start=ORIGIN, end = ORIGIN + 3*RIGHT + 2*UP).add_tip()
        crka_baz_d = TexMobject("\\vec{c}").set_color(WHITE).move_to(vek_baz_d.get_center()+0.35*UP+0.15*LEFT)
        v_b_d = VGroup(vek_baz_d, crka_baz_d)
        """
        self.play(FadeOut(enacba1), FadeOut(v_b_c))
        baza = TextMobject("\"BAZA\"").move_to(ORIGIN + 2*UP)
        self.play(FadeInFromDown(baza))
        self.wait(2)
        self.play(FadeOut(baza)) 
        #sprememba baznih vektorjev
        vek_baz_b_nov = Line(start=ORIGIN, end = ORIGIN + UP + LEFT).set_color(BLUE).add_tip()
        crka_baz_b_nov = TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_baz_b_nov.get_center()+0.35*LEFT + 0.35*DOWN)
        v_b_b_nov = VGroup(vek_baz_b_nov, crka_baz_b_nov)
        vek_baz_a_nov = Line(start=ORIGIN, end = ORIGIN + 2*RIGHT).set_color(RED).add_tip()
        crka_baz_a_nov = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a_nov.get_center()+0.5*DOWN)
        v_b_a_nov = VGroup(vek_baz_a_nov, crka_baz_a_nov)
        self.play(Transform(v_b_a, v_b_a_nov), Transform(v_b_b,v_b_b_nov))
        self.wait(1)
        vek_baz_c2 = Line(start=ORIGIN, end=3*RIGHT + UP).add_tip()
        crka_baz_c2 = TexMobject("\\vec{c}").move_to(vek_baz_c2.get_center() + 0.15*UP + 0.35*LEFT)
        v_b_c2 = VGroup(vek_baz_c2, crka_baz_c2)
        self.play(ShowCreation(v_b_c2))
        self.wait(1)
        rot_matrika = [[2,-1],[0,1]]
        self.play(ApplyMethod(plane.apply_matrix, rot_matrika))
        self.wait(1)
        vek_baz_a_nov2 = Line(start=ORIGIN+ 2*RIGHT, end = ORIGIN + 4*RIGHT).set_color(RED).add_tip()
        crka_baz_a_nov2 = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a_nov2.get_center()+0.5*DOWN)
        v_b_a_nov2 = VGroup(vek_baz_a_nov2, crka_baz_a_nov2)
        self.play(ShowCreation(v_b_a_nov2))
        self.wait(1)
        enacba3 = TexMobject("\\vec{c}"," = 2","\\vec{a}"," + ","\\vec{b}").move_to(2*LEFT + 2*DOWN).set_color_by_tex("{a}", RED).set_color_by_tex("{b}", BLUE)
        self.play(TransformFromCopy(crka_baz_c2, enacba3))
        self.wait(1)
        rot_matrika2 = [[1/2,1/2],[0,1]]
        vek_baz_a3 = Line(start=ORIGIN, end = ORIGIN + RIGHT).set_color(RED).add_tip()
        crka_baz_a3 = TexMobject("\\vec{a}").set_color(RED).move_to(vek_baz_a3.get_center()+0.5*DOWN)
        v_b_a3 = VGroup(vek_baz_a3, crka_baz_a3)
        vek_baz_b3 = Line(start=ORIGIN, end = ORIGIN + UP).set_color(BLUE).add_tip()
        crka_baz_b3 = TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_baz_b3.get_center()+0.5*LEFT)
        v_b_b3 = VGroup(vek_baz_b3, crka_baz_b3)
        self.play(FadeOut(enacba3), FadeOut(v_b_a_nov2), ApplyMethod(plane.apply_matrix, rot_matrika2), Transform(v_b_a, v_b_a3), Transform(v_b_b, v_b_b3), FadeOut(v_b_c2))
        self.wait(1)
        brace1 = Brace(vek_baz_a, DOWN).shift(DOWN)
        brace1text = brace1.get_text("1")
        brace2 = Brace(vek_baz_b, LEFT).shift(LEFT)
        brace2text = brace2.get_text("1")
        self.play(ShowCreation(brace1), Write(brace1text), ShowCreation(brace2), Write(brace2text))
        self.wait(1)
        self.play(FadeOut(brace1),FadeOut(brace2), FadeOut(brace1text), FadeOut(brace2text))
        self.wait(1)
        crka_i = TexMobject("\\vec{i}").move_to(crka_baz_a.get_center()).set_color(RED)
        crka_j = TexMobject("\\vec{j}").move_to(crka_baz_b.get_center()).set_color(BLUE)
        self.play(Transform(crka_baz_a, crka_i),Transform(crka_baz_b, crka_j))
        self.wait(1)
        self.play(FadeOut(plane))
        bazna_vektorja_ij = VGroup(crka_baz_a, crka_baz_b, vek_baz_a, vek_baz_b)
        bazni_vektor_k = Line(start=ORIGIN, end = ORIGIN + np.array([0,0,1])).set_color(GREEN)
        
        sonbr = TextMobject("STANDARDNA ", "ORTONORMIRANA ", "BAZA RAVNINE").move_to(2*UP)
        self.play(FadeInFromDown(sonbr), ApplyMethod(bazna_vektorja_ij.shift,0.5*DOWN))
        self.wait(1)
        self.play(ApplyMethod(sonbr.set_color_by_tex, "STANDARDNA ", YELLOW))
        self.wait(1)
        self.play(ApplyMethod(sonbr.set_color_by_tex, "STANDARDNA ", WHITE))
        self.play(ApplyMethod(sonbr.set_color_by_tex, "ORTONORMIRANA ", YELLOW))
        pravi_kot = Elbow().shift(0.5*DOWN)
        self.play(ShowCreation(pravi_kot))
        self.wait(1)
        self.play(ApplyMethod(sonbr.set_color_by_tex, "ORTONORMIRANA ", WHITE), FadeOut(pravi_kot))
        self.play(ApplyMethod(sonbr.set_color_by_tex, "BAZA RAVNINE", YELLOW))
        self.wait(1)
        self.play(ApplyMethod(sonbr.set_color_by_tex, "BAZA RAVNINE", WHITE))
        self.wait(1)
        self.play(ApplyMethod(bazna_vektorja_ij.shift,0.5*UP), FadeOut(sonbr))
        self.wait(1)
        self.play(FadeOut(crka_baz_a),FadeOut(crka_baz_b), run_time=0.3)
        zeleni_trikotnik = Polygon(1.2*UP, ORIGIN + 0.85*UP - 0.15*LEFT, ORIGIN + 0.85*UP + 0.15*LEFT).set_color(GREEN).set_fill(GREEN, opacity=1)
        self.move_camera(phi=math.pi/4, theta=math.pi/4, gamma=0, distance=2)
        self.add_fixed_in_frame_mobjects(zeleni_trikotnik)
        self.play(FadeOut(zeleni_trikotnik), run_time=0)
        self.play(ShowCreation(bazni_vektor_k), run_time=0.5)
        self.play(ShowCreation(zeleni_trikotnik))
        """
        zamrznjeno_polje = NumberPlane()
        self.add_fixed_in_frame_mobjects(zamrznjeno_polje)
        self.play(ShowCreation(zamrznjeno_polje))
        """
        crka_i_3d = TexMobject("\\vec{i}").move_to(0.8*LEFT + 1.2*DOWN).set_color(RED)
        crka_j_3d = TexMobject("\\vec{j}").move_to(0.8*RIGHT + 1.2*DOWN).set_color(BLUE)
        crka_k_3d = TexMobject("\\vec{k}").move_to(1.75*UP).set_color(GREEN)
        self.add_fixed_in_frame_mobjects(crka_i_3d)
        #self.play(FadeOut(crka_i_3d), run_time=0)
        self.add_fixed_in_frame_mobjects(crka_j_3d)
        #self.play(FadeOut(crka_j_3d), run_time=0)
        self.add_fixed_in_frame_mobjects(crka_k_3d)
        #self.play(FadeOut(crka_k_3d), run_time=0)
        self.play(Write(crka_i_3d),Write(crka_j_3d),Write(crka_k_3d))
        self.wait(1)
        
        #plane = NumberPlane()
        bela_crtkasta1 = DashedLine(start = ORIGIN, end = 1.5*(1.8*RIGHT + 1.25*UP))
        bela_crtkasta2 = DashedLine(start = ORIGIN + 0.5*(1.8*RIGHT - 1.25*UP), end = 1.5*(1.8*RIGHT - 1.25*UP))
        bela_crtkasta3 = DashedLine(start = 1.2*UP, end = 3*UP)
        bela_crtkasta4 = DashedLine(start = ORIGIN + 0.5*(-1.8*RIGHT - 1.25*UP), end = 1.5*(-1.8*RIGHT - 1.25*UP))
        self.add_fixed_in_frame_mobjects(bela_crtkasta1)
        self.add_fixed_in_frame_mobjects(bela_crtkasta2)
        self.add_fixed_in_frame_mobjects(bela_crtkasta3)
        self.add_fixed_in_frame_mobjects(bela_crtkasta4)
        self.play(FadeOut(bela_crtkasta1),FadeOut(bela_crtkasta2),FadeOut(bela_crtkasta3),FadeOut(bela_crtkasta4),run_time=0)
        self.remove(bela_crtkasta1)
        self.remove(bela_crtkasta2)
        #self.add_fixed_in_frame_mobjects(plane)
        #self.add(plane)
        sonbp = TextMobject("STANDARDNA ", "ORTONORMIRANA ", "BAZA PROSTORA").move_to(3*UP)
        self.add_fixed_in_frame_mobjects(sonbp)
        self.play(FadeInFromDown(sonbp))
        self.wait(1)
        self.play(ApplyMethod(sonbp.set_color_by_tex,"BAZA PROSTORA", YELLOW))
        self.wait(1)
        self.play(FadeOut(sonbp), ApplyMethod(crka_k_3d.shift,0.3*LEFT))
        self.wait(0.5)
        self.play(ShowCreation(bela_crtkasta1),ShowCreation(bela_crtkasta2),ShowCreation(bela_crtkasta3),ShowCreation(bela_crtkasta4))
        self.wait(1)
        vek_a_3d = Line(start=ORIGIN, end=3.5*RIGHT + 1.2*UP).add_tip().set_color(ORANGE)
        self.add_fixed_in_frame_mobjects(vek_a_3d)
        crka_a_3d = TexMobject("\\vec{a}").move_to(1.75*RIGHT + 0.3*UP).set_color(ORANGE)
        self.add_fixed_in_frame_mobjects(crka_a_3d)
        self.play(ShowCreation(vek_a_3d), Write(crka_a_3d))
        self.wait(1)
        crtasta_navpicna = DashedLine(start=3.5*RIGHT + 1.2*UP, end = 3.5*RIGHT).set_color(GREEN)
        crtasta_60 = DashedLine(start=3.5*RIGHT, end = 1.8*RIGHT+ 1.25*DOWN).set_color(RED)
        crtasta_120 = DashedLine(start=3.5*RIGHT, end = 1.8*RIGHT + 1.25*UP).set_color(BLUE)
        self.add_fixed_in_frame_mobjects(crtasta_navpicna, crtasta_60, crtasta_120)
        self.play(ShowCreation(crtasta_navpicna), ShowCreation(crtasta_60), ShowCreation(crtasta_120))
        self.wait(1)
        #self.play(ApplyMethod(crtasta_navpicna.set_color, GREEN),ApplyMethod(crtasta_60.set_color, RED),ApplyMethod(crtasta_120.set_color, BLUE))
        enacba_a = TexMobject("\\vec{a}"," = -2","\\vec{i}"," + 2","\\vec{j}"," + ","\\vec{k}").set_color_by_tex("{i}", RED).set_color_by_tex("{j}", BLUE).set_color_by_tex("{k}", GREEN).move_to(-4*RIGHT + 0.5*UP).set_color_by_tex("{a}",ORANGE)
        self.add_fixed_in_frame_mobjects(enacba_a)
        self.play(Write(enacba_a))
        self.wait(1)
        enacba_a2 = TexMobject("\\vec{a}"," = (","-2",",","2",",","1",")").set_color_by_tex("2", BLUE).set_color_by_tex("-2", RED).set_color_by_tex("1", GREEN).move_to(-4*RIGHT - 0.5*UP).set_color_by_tex("{a}",ORANGE)
        self.add_fixed_in_frame_mobjects(enacba_a2)
        self.play(Write(enacba_a2))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.wait(1)
        
        """
        vek_a2_3d = Line(start=ORIGIN, end=2.65*RIGHT + 1.8*UP).add_tip()
        #self.add_fixed_in_frame_mobjects(vek_a2_3d)
        crka_a2_3d = TexMobject("\\vec{a}").move_to(1.75*RIGHT + 1.5*UP)
        #self.add_fixed_in_frame_mobjects(crka_a2_3d)

        self.play(Transform(vek_a_3d, vek_a2_3d), Transform(crka_a_3d, crka_a2_3d))
        self.wait(1)
        """
        
        #zdaj je konec te scene, ker je kamera čisto uničena
        
        """
        self.move_camera(0.8*np.pi/2, -0.45*np.pi)
        self.begin_ambient_camera_rotation()
        krog = Circle().set_color(RED)
        self.play(ShowCreation(krog))
        self.wait(6)
        self.move_camera(np.pi/4, np.pi/4, 2)
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.set_camera_to_default_position()
        self.move_camera(0.8*np.pi/2, -0.45*np.pi)
        self.stop_ambient_camera_rotation()
        self.set_camera_to_default_position()
        self.wait(2)
        self.move_camera(0.8*np.pi/2, -0.45*np.pi)
        """
class KoordinatniZapis(Scene):
    def construct(self):
        plane = NumberPlane()
        self.play(ShowCreation(plane))
        vek_a = Line(start = ORIGIN, end = 3*RIGHT + DOWN).add_tip().set_color(RED)
        crka_a = TexMobject("\\vec{a}").move_to(vek_a.get_center() + 0.3*DOWN + 0.3*LEFT).set_color(RED)
        vek_b = Line(start = ORIGIN, end = 2*UP + RIGHT).add_tip().set_color(BLUE)
        crka_b = TexMobject("\\vec{b}").move_to(vek_b.get_center() - 0.3*LEFT - 0.3*UP).set_color(BLUE)
        vek_b2 = Line(start = 3*RIGHT + DOWN, end = UP + 4*RIGHT).add_tip().set_color(BLUE)
        crka_b2 = TexMobject("\\vec{b}").move_to(vek_b2.get_center() - 0.3*LEFT - 0.3*UP).set_color(BLUE)
        v_a = VGroup(vek_a, crka_a)
        v_b = VGroup(vek_b, crka_b)
        v_b2 = VGroup(vek_b2, crka_b2)
        vek_ab = Line(start = ORIGIN, end = UP + 4*RIGHT).add_tip().set_color(PURPLE)
        crka_ab = TexMobject("\\vec{a} + \\vec{b}").move_to(vek_ab.get_center() + 0.4*UP + 0.2*LEFT).set_color(PURPLE)
        
        self.play(ShowCreation(v_a), ShowCreation(v_b))
        self.wait(1)
        enacba_a = TexMobject("\\vec{a}"," = (","3",",","\\text{-}1",")").move_to(1.5*UP + 3.82*LEFT).set_color_by_tex("{a}",RED)
        enacba_b = TexMobject("\\vec{b}"," = (","1",",","2",")").move_to(0.5*UP + 3.88*LEFT).set_color_by_tex("{b}",BLUE)
        enacba_c1 = TexMobject("\\vec{a} + \\vec{b}").set_color(PURPLE)
        enacba_c2 = TexMobject("=(")
        enacba_c3 = TexMobject("4").set_color(YELLOW)
        enacba_c4 = TexMobject(",")
        enacba_c5 = TexMobject("1").set_color(YELLOW)
        enacba_c6 = TexMobject(")")
        enacba_c = VGroup(enacba_c1, enacba_c2, enacba_c3, enacba_c4, enacba_c5, enacba_c6)
        enacba_c.arrange_submobjects(RIGHT)
        enacba_c1.shift(0.1*UP)
        enacba_c3.shift(0.2*LEFT)
        enacba_c4.shift(0.4*LEFT + 0.2*DOWN)
        enacba_c5.shift(0.5*LEFT)
        enacba_c6.shift(0.7*LEFT)
        enacba_c.move_to(-0.5*UP + 4.4*LEFT)
        prispevek_ax = Line(start=2*DOWN, end = 2*DOWN + 3*RIGHT).add_tip().set_color(RED)
        prispevek_bx = Line(start=2*DOWN + 3*RIGHT, end = 2*DOWN + 4*RIGHT).add_tip().set_color(BLUE)
        prispevek_ay = Line(start=5*RIGHT, end = DOWN + 5*RIGHT).add_tip().set_color(RED)
        prispevek_by = Line(start=5.5*RIGHT +DOWN, end = UP + 5.5*RIGHT).add_tip().set_color(BLUE)
        prispevek_x = VGroup(prispevek_ax,prispevek_bx)
        prispevek_y = VGroup(prispevek_ay,prispevek_by)
        vijolicni_x = Line(start=2*DOWN, end = 2*DOWN + 4*RIGHT).add_tip().set_color(PURPLE)
        vijolicni_y = Line(start=5*RIGHT, end = UP + 5*RIGHT).add_tip().set_color(PURPLE)
        self.play(ShowCreation(enacba_a), ShowCreation(enacba_b))
        self.wait(1)
        self.play(Transform(v_b,v_b2))
        self.wait(1)
        self.play(ShowCreation(vek_ab), Write(crka_ab))
        self.wait(1)
        self.play(Write(enacba_c1),Write(enacba_c2),Write(enacba_c4),Write(enacba_c6))
        self.wait(1)
        self.play(ApplyMethod(enacba_a.set_color_by_tex, "3", YELLOW), ApplyMethod(enacba_b.set_color_by_tex, "1", YELLOW), ShowCreation(prispevek_ax),ShowCreation(prispevek_bx))
        self.play(Write(enacba_c3))
        self.wait(1)
        self.play(ApplyMethod(enacba_a.set_color_by_tex, "3", WHITE), ApplyMethod(enacba_b.set_color_by_tex, "1", WHITE), ApplyMethod(enacba_c3.set_color, WHITE), Transform(prispevek_x, vijolicni_x))
        self.play(ApplyMethod(enacba_a.set_color_by_tex, "\\text{-}1", YELLOW), ApplyMethod(enacba_b.set_color_by_tex, "2", YELLOW), ShowCreation(prispevek_ay),ShowCreation(prispevek_by))
        self.play(Write(enacba_c5))
        self.wait(1)
        self.play(ApplyMethod(enacba_a.set_color_by_tex, "\\text{-}1", WHITE), ApplyMethod(enacba_b.set_color_by_tex, "2", WHITE), ApplyMethod(enacba_c5.set_color, WHITE), Transform(prispevek_y, vijolicni_y))
        self.wait(1)
        self.play(ApplyMethod(prispevek_x.shift, 2*UP),ApplyMethod(prispevek_y.shift, LEFT), FadeOut(v_a), FadeOut(v_b))
        self.wait(1)
        spodnji_napis = TexMobject("a_1"," + ","b_1").set_color_by_tex("a_1", RED).set_color_by_tex("b_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("b_2", BLUE).move_to(2*RIGHT + 1*DOWN)
        desni_napis = TexMobject("a_2"," + ","b_2").set_color_by_tex("a_1", RED).set_color_by_tex("b_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("b_2", BLUE).move_to(5.5*RIGHT + 0.5*UP)
        brace_spodnji = Brace(prispevek_x, DOWN)
        brace_desni = Brace(prispevek_y, RIGHT)
        ena = TexMobject("1").move_to(5.5*RIGHT + 0.5*UP)
        stiri = TexMobject("4").move_to(2*RIGHT + 1*DOWN)
        self.play(ShowCreation(brace_spodnji), ShowCreation(brace_desni))
        self.wait(1)
        self.play(Write(spodnji_napis),Write(desni_napis))
        self.wait(1)
        self.play(Transform(spodnji_napis, stiri), Transform(desni_napis, ena))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.wait(1)
        splosna_enacba_sestevanja = TexMobject("(","a_1",",","a_2",") + (","b_1",", ","b_2",") = (","a_1 + b_1",", ","a_2 + b_2",")")
        splosna_enacba_sestevanja.set_color_by_tex("a_1", RED).set_color_by_tex("b_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("b_2", BLUE)
        self.play(FadeIn(splosna_enacba_sestevanja))
        self.wait(1)
        """
        self.play(ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_1", YELLOW), run_time=0.3)
        self.play(ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "b_1", YELLOW), run_time=0.3)
        self.play(ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_1 + b_1", YELLOW), run_time=0.3)
        self.wait(1)
        self.play(ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_2", YELLOW),ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "b_2", YELLOW), ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_2 + b_2", YELLOW), ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_1", WHITE),ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "b_1", WHITE), ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_1 + b_1", WHITE))
        self.wait(1)
        self.play(ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_2", WHITE),ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "b_2", WHITE), ApplyMethod(splosna_enacba_sestevanja.set_color_by_tex, "a_2 + b_2", WHITE))
        self.wait(1)
        """
        splosna_enacba_sestevanja3 = TexMobject("(","a_1",", ","a_2",", ","a_3",") + (","b_1",", ","b_2",", ","b_3",") = (","a_1 + b_1",", ","a_2 + b_2",", ","a_3 + b_3",")")
        splosna_enacba_sestevanja3.set_color_by_tex("a_1", RED).set_color_by_tex("b_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("b_2", BLUE).set_color_by_tex("a_3", GREEN).set_color_by_tex("b_3", GREEN)
        self.play(FadeIn(splosna_enacba_sestevanja3), ApplyMethod(splosna_enacba_sestevanja.shift, 2*UP))
        self.wait(1)
        splosna_enacba_sestevanja_n = TexMobject("(","a_1",", ","\\ldots",", ","a_n",") + (","b_1",", ","\\ldots",", ","b_n",") = (","a_1 + b_1",", ","\\ldots",", ","a_n + b_n",")").shift(2*DOWN)
        splosna_enacba_sestevanja_n.set_color_by_tex("a_1", RED).set_color_by_tex("b_1", RED).set_color_by_tex("ldots", BLUE).set_color_by_tex("b_2", BLUE).set_color_by_tex("a_n", GREEN).set_color_by_tex("b_n", GREEN)
        self.play(FadeIn(splosna_enacba_sestevanja_n))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.play(ShowCreation(plane))
        v_a.set_color(RED)
        self.play(ShowCreation(v_a))
        enacba_a = TexMobject("\\vec{a}"," = (","3",",","-1",")").move_to(1.5*UP + 3.82*LEFT).set_color_by_tex("{a}", RED)
        self.play(Write(enacba_a))
        enacba_2a = TexMobject("2","\\vec{a}"," = (","6",",","-2",")").move_to(0.5*UP + 3.8*LEFT).set_color_by_tex("{a}", RED)
        self.wait(1)
        vek_2a = Line(start = ORIGIN, end = 6*RIGHT + 2*DOWN).add_tip().set_color(RED)
        crka_2a = TexMobject("2","\\vec{a}").move_to(vek_2a.get_center() + 0.3*DOWN + 0.3*LEFT).set_color_by_tex("{a}", RED)
        v_2a = VGroup(vek_2a, crka_2a)
        self.play(Transform(v_a, v_2a),TransformFromCopy(enacba_a,enacba_2a))
        self.wait(1)
        vek_05a = Line(start = ORIGIN, end = -3*RIGHT - 1*DOWN).add_tip().set_color(RED)
        crka_05a = TexMobject("-","\\vec{a}").move_to(vek_05a.get_center() + 0.3*DOWN + 0.3*LEFT).set_color_by_tex("{a}", RED)
        v_05a = VGroup(vek_05a, crka_05a)
        enacba_05a = TexMobject("-","\\vec{a}"," = (","-3",",","1",")").move_to(-0.5*UP + 4.8*LEFT  + 8*RIGHT).set_color_by_tex("{a}", RED)
        self.play(ApplyMethod(enacba_a.shift, 7*RIGHT), ApplyMethod(enacba_2a.shift, 7*RIGHT), Transform(v_a, v_05a), run_time=1)
        self.play(FadeInFromDown(enacba_05a))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        splosno_mnozenje_s_skalarjem = TexMobject("n","(a_1, a_2) = (","n","a_1,"," n","a_2)").shift(1.5*UP).set_color_by_tex("n",RED)
        splosno_mnozenje_s_skalarjem3 = TexMobject("n","(a_1, a_2, a_3) = (","n","a_1, ","n","a_2, ","n","a_3)").set_color_by_tex("n",RED)
        splosno_mnozenje_s_skalarjemk = TexMobject("n","(a_1, \\ldots,  a_k) = (","n","a_1, \\ldots, ","n","a_k)").shift(-1.5*UP).set_color_by_tex("n",RED)
        self.play(FadeInFromDown(splosno_mnozenje_s_skalarjem))
        self.wait(1)
        self.play(FadeInFromDown(splosno_mnozenje_s_skalarjem3))
        self.wait(1)
        self.play(FadeInFromDown(splosno_mnozenje_s_skalarjemk))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.play(ShowCreation(plane))
        vek_dolzina = Line(start = ORIGIN, end=3*RIGHT + 2*UP).add_tip().set_color(ORANGE)
        crka_vek_dolzina = TexMobject("\\vec{a}").move_to(vek_dolzina.get_center() - 0.2*DOWN - 0.5*RIGHT).set_color(ORANGE)
        crka_dolzina = TexMobject("\\lvert \\vec{a} \\rvert").move_to(vek_dolzina.get_center() - 0.2*DOWN - 0.5*RIGHT).set_color(ORANGE)
        enacba_dolzina_1 = TexMobject("\\vec{a}"," = (","a_1",", ","a_2",")").move_to(4*LEFT + 1.5*UP).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("\\vec{a}", ORANGE)
        enacba_dolzina_2 = TexMobject("\\lvert \\vec{a} \\rvert"," =").move_to(4.8*LEFT + 0.5*UP).set_color_by_tex("\\vec{a}", ORANGE)
        enacba_dolzina_2_2 = TexMobject("?").next_to(enacba_dolzina_2, RIGHT)
        self.play(ShowCreation(vek_dolzina), Write(crka_vek_dolzina))
        self.wait(1)
        self.play(Write(enacba_dolzina_1))
        self.wait(1)
        self.play(Write(enacba_dolzina_2), Write(enacba_dolzina_2_2))
        self.wait(1)
        self.play(Transform(crka_vek_dolzina, crka_dolzina))
        self.wait(1)
        line_a1 = Line(start=ORIGIN, end= 3*RIGHT).set_color(RED)
        line_a2 = Line(start = 3*RIGHT, end = 3*RIGHT + 2*UP).set_color(BLUE)
        self.play(ShowCreation(line_a1))
        brace_l1 = Brace(line_a1, direction=DOWN).set_color(RED)
        brace_l1text = brace_l1.get_tex("a_1").set_color(RED)
        self.play(ShowCreation(brace_l1), Write(brace_l1text))
        self.wait(1)
        self.play(ShowCreation(line_a2))
        brace_l2 = Brace(line_a2, direction=RIGHT).set_color(BLUE)
        brace_l2text = brace_l2.get_tex("a_2").set_color(BLUE)
        self.play(ShowCreation(brace_l2), Write(brace_l2text))
        self.wait(1)
        pitagorov_izrek = TexMobject("{\\lvert \\vec{a} \\rvert}","^2 = ","{a_1}","^2 + ","{a_2}","^2").move_to(4*LEFT + 0.5*DOWN).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("{\\lvert \\vec{a} \\rvert}", ORANGE)
        posledica_pitag_izreka = TexMobject("{\\lvert \\vec{a} \\rvert}"," = \\sqrt{(","{a_1}","^2 + ","{a_2}","^2",")}").move_to(4*LEFT + 1.5*DOWN).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("{\\lvert \\vec{a} \\rvert}", ORANGE)
        self.play(FadeInFromDown(pitagorov_izrek))
        self.wait(1)
        self.play(FadeInFromDown(posledica_pitag_izreka))
        self.wait(1)
        okvir = SurroundingRectangle(posledica_pitag_izreka).set_color(RED)
        self.play(ShowCreation(okvir))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        posledica_pitag_izreka.move_to(ORIGIN + 1.5*UP)
        posledica_pitag_izreka2 = TexMobject("{\\lvert \\vec{a} \\rvert}"," = \\sqrt{(","{a_1}","^2 + ","{a_2}","^2","+","{a_3}","^2",")}").move_to(ORIGIN).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("a_3", GREEN).set_color_by_tex("{\\lvert \\vec{a} \\rvert}", ORANGE)
        posledica_pitag_izreka3 = TexMobject("{\\lvert \\vec{a} \\rvert}"," = \\sqrt{(","{a_1}","^2 + ","\\ldots","+","{a_n}","^2",")}").move_to(ORIGIN).set_color_by_tex("a_1", RED).set_color_by_tex("\\ldots", BLUE).set_color_by_tex("a_n", GREEN).move_to(ORIGIN - 1.5*UP).set_color_by_tex("{\\lvert \\vec{a} \\rvert}", ORANGE)
        self.play(FadeInFromDown(posledica_pitag_izreka))
        self.wait(2)
        self.play(FadeInFromDown(posledica_pitag_izreka2))
        self.wait(2)
        self.play(FadeInFromDown(posledica_pitag_izreka3))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.wait(1)
        
        
        #zdaj je treba narediti še dolžino vektorja s pitagorovim izrekom
            
class SkalarniProdukt(Scene):
    def construct(self):
        skalarni_produkt = TextMobject("Skalarni produkt").scale(2.5)
        self.play(FadeIn(skalarni_produkt))
        self.wait(2)
        self.play(FadeOut(skalarni_produkt))
        enacba_skal_1 = TexMobject("\\vec{vektor}","\\cdot","\\vec{vektor}").shift(1*LEFT)
        enacba_skal_2 = TexMobject("= skalar").next_to(enacba_skal_1, RIGHT).shift(0.09*DOWN)
        self.play(FadeInFromDown(enacba_skal_1))
        self.wait(1)
        self.play(FadeInFromDown(enacba_skal_2))
        self.wait(1)
        self.play(ApplyMethod(enacba_skal_1.set_color_by_tex, "\\cdot", RED))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        vek_skal_a = Line(start=ORIGIN + LEFT, end = 3*RIGHT + LEFT).add_tip().set_color(RED)
        crka_skal_a = TexMobject("\\vec{a}").set_color(RED).move_to(vek_skal_a.get_center() + 0.5*UP + 0.5*RIGHT)
        vek_skal_b = Line(start=ORIGIN + LEFT, end = 1.25*RIGHT + 2*UP + LEFT).add_tip().set_color(BLUE)
        crka_skal_b = TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_skal_b.get_center() + 0.3*LEFT + 0.2*UP)
        self.play(ShowCreation(vek_skal_a), ShowCreation(vek_skal_b), Write(crka_skal_a), Write(crka_skal_b))
        self.wait(1)
        navpicna_projekcija = DashedLine(end=1.25*RIGHT + LEFT, start = 1.25*RIGHT + 2*UP + LEFT)
        pravi_kot_skal = Elbow().shift(0.25*RIGHT)
        self.play(ShowCreation(navpicna_projekcija), ShowCreation(pravi_kot_skal))
        nevidna_1 = Line(start=ORIGIN + LEFT, end = 1.25*RIGHT + LEFT)
        brace_nevidna_1 = Brace(nevidna_1, DOWN)
        brace_nevidna_1text = brace_nevidna_1.get_tex("\\lvert \\vec{b} \\rvert '").set_color(BLUE)
        nevidna_2 = Line(start=ORIGIN + LEFT, end = 3*1.25*RIGHT + LEFT)
        brace_nevidna_2 = Brace(nevidna_2, DOWN)
        brace_nevidna_2text = brace_nevidna_2.get_tex("\\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert '").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        brace_nevidna_2text2 = brace_nevidna_2.get_tex("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert '").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        self.wait(1)
        self.play(ShowCreation(brace_nevidna_1), Write(brace_nevidna_1text))
        self.wait(1)
        self.play(Transform(brace_nevidna_1,brace_nevidna_2), Transform(brace_nevidna_1text, brace_nevidna_2text))
        self.wait(1)
        self.play(Transform(brace_nevidna_1text, brace_nevidna_2text2))
        self.wait(1)
        fi= Arc(
                    radius=0.8,
                    start_angle=vek_skal_a.get_angle(),
                    angle =vek_skal_b.get_angle(),
                    color=WHITE
            ).shift(LEFT)
        crka_fi = TexMobject("\\varphi").move_to(0.53*LEFT + 0.27*UP).scale(0.8)
        self.play(ShowCreation(fi))
        self.play(Write(crka_fi), run_time=0.5)
        self.wait(1)
        self.play(ApplyMethod(brace_nevidna_1text.shift, 2*DOWN), ApplyMethod(brace_nevidna_1.shift, 2*DOWN))
        brace_nevidna_1_ = Brace(nevidna_1, DOWN)
        brace_nevidna_1text_ = brace_nevidna_1_.get_tex("\\lvert \\vec{b} \\rvert '","=","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}").set_color_by_tex("{b}",BLUE)
        self.play(ShowCreation(brace_nevidna_1_))
        self.wait(1)
        self.play(Write(brace_nevidna_1text_))
        self.wait(1)
        self.play(FadeOut(brace_nevidna_1_), ApplyMethod(brace_nevidna_1text_.shift, 4*LEFT + UP), ApplyMethod(brace_nevidna_1text.shift, 2*UP), ApplyMethod(brace_nevidna_1.shift, 2*UP))
        self.wait(1)
        koncni_tekst = brace_nevidna_1.get_tex("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        self.play(Transform(brace_nevidna_1text, koncni_tekst))
        self.wait(1)
        okvir_skal = SurroundingRectangle(koncni_tekst).set_color(YELLOW)
        self.play(ShowCreation(okvir_skal))
        self.wait(1)
        self.play(ApplyMethod(crka_skal_a.shift,1.2*RIGHT),FadeOut(pravi_kot_skal), FadeOut(navpicna_projekcija), FadeOut(brace_nevidna_1), FadeOut(brace_nevidna_1text_))
        druga_projekcija = DashedLine(start=2*RIGHT,end = LEFT + 0.843*RIGHT + 1.348*UP)
        drugi_pravi_kot = Elbow().move_to(LEFT + 0.99*RIGHT + 1.348*UP).rotate(-(math.pi/2 -1.012))
        self.play(ShowCreation(druga_projekcija), ShowCreation(drugi_pravi_kot))
        self.wait(1)
        koncni_tekst2 = brace_nevidna_1.get_tex("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}","=","\\vec{b}","\\cdot","\\vec{a}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        okvir_skal2 = SurroundingRectangle(koncni_tekst2).set_color(YELLOW)
        self.play(Transform(brace_nevidna_1text, koncni_tekst2), Transform(okvir_skal,okvir_skal2))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        vek_prikaz_1 = Line(start=ORIGIN,end = 3*RIGHT).add_tip().set_color(RED)
        crka_prikaz_1 = TexMobject("\\vec{a}").set_color(RED).move_to(vek_prikaz_1.get_center() + 0.5*DOWN)
        v_prikaz_1 = VGroup(vek_prikaz_1, crka_prikaz_1)
        vek_prikaz_2_1 = Line(start=ORIGIN, end = RIGHT + math.sqrt(3)*UP).add_tip().set_color(BLUE)
        crka_prikaz_2_1= TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_prikaz_2_1.get_center() + 0.2*UP + 0.4*LEFT)
        v_prikaz_2_1 = VGroup(vek_prikaz_2_1, crka_prikaz_2_1)
        splosna_enacba_skal = TexMobject("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(4*LEFT + 1.5*UP)
        splosna_enacba_skal_brez = TexMobject("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(4*LEFT + 1.5*UP)
        sprednja_stevilka = DecimalNumber(1, num_decimal_places=2)
        #splosna_prvi = TexMobject("\\vec{a}","\\cdot","\\vec{b}","=").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        #splosna_drugi = TexMobject(" \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        #splosna_enacba_skal_ena = VGroup(splosna_prvi, splosna_drugi)
        #splosna_enacba_skal_ena.arrange_submobjects(RIGHT).move_to(4*LEFT + 1.5*UP)
        splosna_enacba_skal_pravi = TexMobject("\\vec{a}","\\cdot","\\vec{b}","=","0").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(4.3*LEFT + 1.6*UP)
        splosna_enacba_skal_minus = TexMobject("\\vec{a}","\\cdot","\\vec{b}","=","-","\\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(4*LEFT + 1.5*UP)
        self.play(ShowCreation(v_prikaz_1),ShowCreation(v_prikaz_2_1))
        self.wait(1)
        self.play(FadeInFromDown(splosna_enacba_skal))
        self.wait(1)
        vek_prikaz_2_2 = Line(start=ORIGIN, end = 2*RIGHT).add_tip().set_color(BLUE)
        crka_prikaz_2_2 = TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_prikaz_2_2.get_center() + 0.5*UP)
        v_prikaz_2_2 = VGroup(vek_prikaz_2_2, crka_prikaz_2_2)
        self.play(Transform(v_prikaz_2_1, v_prikaz_2_2), Transform(splosna_enacba_skal, splosna_enacba_skal_brez))
        self.wait(1)
        """
        sprednja_stevilka.next_to(splosna_prvi, RIGHT).shift(0.05*DOWN)
        self.play(ApplyMethod(splosna_drugi.shift, RIGHT), Write(sprednja_stevilka))
        self.wait(1)
        """
        vek_prikaz_2_3 = Line(start=ORIGIN, end = 2*UP).add_tip().set_color(BLUE)
        crka_prikaz_2_3= TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_prikaz_2_3.get_center() + 0.5*LEFT)
        v_prikaz_2_3 = VGroup(vek_prikaz_2_3, crka_prikaz_2_3)
        pravi_kot_skal2 = Elbow()
        self.play(Transform(v_prikaz_2_1, v_prikaz_2_3), ShowCreation(pravi_kot_skal2), Transform(splosna_enacba_skal, splosna_enacba_skal_pravi), run_time=1)
        #self.play(, run_time=1)
        self.wait(1)
        vek_prikaz_2_4 = Line(start=ORIGIN, end = 2*LEFT).add_tip().set_color(BLUE)
        crka_prikaz_2_4= TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_prikaz_2_4.get_center() + 0.5*DOWN)
        v_prikaz_2_4 = VGroup(vek_prikaz_2_4, crka_prikaz_2_4)
        
        vek_prikaz_2_5 = Line(start=ORIGIN, end = (1.41)*LEFT + (1.41)*UP).add_tip().set_color(BLUE)
        crka_prikaz_2_5= TexMobject("\\vec{b}").set_color(BLUE).move_to(vek_prikaz_2_5.get_center() + 0.4*LEFT)
        v_prikaz_2_5 = VGroup(vek_prikaz_2_5, crka_prikaz_2_5)
        #self.play(ApplyMethod(splosna_prvi.shift, 3.5*DOWN), ApplyMethod(splosna_drugi.shift, 3.5*DOWN), ApplyMethod(sprednja_stevilka.shift, 3.5*DOWN))
        #self.play(ApplyMethod(splosna_drugi.shift, 0.3*RIGHT), run_time=0.7)
        kot_180= Arc(
                    radius=0.6,
                    start_angle=vek_skal_a.get_angle(),
                    angle =vek_prikaz_2_4.get_angle(),
                    color=WHITE
            )
        stopinje_180 = TextMobject("180°").scale(0.6).move_to(kot_180.get_center())
        self.play(FadeOut(pravi_kot_skal2), Transform(v_prikaz_2_1,v_prikaz_2_4), Transform(splosna_enacba_skal,splosna_enacba_skal_minus), ShowCreation(kot_180), Write(stopinje_180))
        self.wait(2)
        self.play(FadeOut(splosna_enacba_skal), FadeOut(kot_180), FadeOut(stopinje_180), Transform(v_prikaz_2_1, v_prikaz_2_5))
        kot_135= Arc(
                    radius=0.7,
                    start_angle=vek_skal_a.get_angle(),
                    angle =vek_prikaz_2_5.get_angle(),
                    color=WHITE
            )
        stopinje_135 = TextMobject("135°").scale(0.6).move_to(kot_135.get_center())
        kot_225= Arc(
                    radius=0.7,
                    start_angle=3*PI/4,
                    angle = 5*PI/4,
                    color=WHITE
            )
        stopinje_225 = TextMobject("225°").scale(0.6).move_to(kot_225.get_center() + 0.1*DOWN + 0.1*LEFT)
        self.play(ShowCreation(kot_135), Write(stopinje_135))
        self.wait(1)
        self.play(Transform(kot_135,kot_225), Transform(stopinje_135,stopinje_225))
        self.wait(1)
        razlog = TexMobject("\\cos(\\varphi) = \\cos(360\\text{°} - \\varphi)").shift(2*DOWN)
        self.play(FadeInFrom(razlog, direction=UP))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        #tukaj je zapis s koordinatami
        prva_stevika = DecimalNumber(5, num_decimal_places=0)
        druga_stevilka = DecimalNumber(3, num_decimal_places=0)
        tretja_stevilka = DecimalNumber(2, num_decimal_places=0)
        cetrta_stevilka = DecimalNumber(-1, num_decimal_places=0)
        enacba_skal_1_1 = TexMobject("(")
        enacba_skal_1_2 = prva_stevika
        enacba_skal_1_3 = TexMobject(",")
        enacba_skal_1_4 = druga_stevilka
        enacba_skal_1_5 = TexMobject(")")
        pika = TexMobject("\\cdot")
        enacba_skal_2_1 = TexMobject("(")
        enacba_skal_2_2 = tretja_stevilka
        enacba_skal_2_3 = TexMobject(",")
        enacba_skal_2_4 = cetrta_stevilka
        enacba_skal_2_5 = TexMobject(")")
        v_skal_1 = VGroup(enacba_skal_1_1,enacba_skal_1_2,enacba_skal_1_3,enacba_skal_1_4,enacba_skal_1_5, pika, enacba_skal_2_1,enacba_skal_2_2,enacba_skal_2_3,enacba_skal_2_4,enacba_skal_2_5)
        
        
        v_skal_1.arrange_submobjects(RIGHT)
        enacba_skal_1_3.shift(0.2*DOWN + 0.2*LEFT).shift(0.1*RIGHT).shift(0.1*RIGHT)
        enacba_skal_2_3.shift(0.2*DOWN + 0.2*LEFT)
        enacba_skal_2_4.shift(0.2*LEFT)
        enacba_skal_2_5.shift(0.2*LEFT)
        enacba_skal_1_4.shift(0.2*LEFT).shift(0.1*RIGHT).shift(0.1*RIGHT)
        enacba_skal_1_5.shift(0.2*LEFT).shift(0.1*RIGHT).shift(0.1*RIGHT)
        enacba_skal_1_1.shift(0.1*RIGHT).shift(0.1*RIGHT).shift(0.1*RIGHT)
        enacba_skal_2_5.shift(0.1*LEFT)
        enacba_skal_1_5.shift(0.1*LEFT)
        enacba_skal_2_1.shift(0.1*RIGHT)
        enacba_skal_1_2.shift(0.1*RIGHT).shift(0.1*RIGHT)
        v_skal_1.shift(1.5*LEFT)
        
        enacba_3_0 = TexMobject("=")
        enacba_3_1 = TexMobject("10").set_color(YELLOW)        
        enacba_3_2 = TexMobject("-")        
        enacba_3_3 = TexMobject("3").set_color(YELLOW)
        enacba_3_4 = TexMobject("=")
        enacba_3_5 = TexMobject("7").set_color(YELLOW)
        enacba_3 = VGroup(enacba_3_0,enacba_3_1, enacba_3_2, enacba_3_3, enacba_3_4, enacba_3_5)
        enacba_3.arrange_submobjects(RIGHT)
        enacba_3.next_to(v_skal_1, RIGHT)
        self.play(Write(v_skal_1))
        self.wait(1)
        self.play(FadeInFromDown(enacba_3_0))
        self.play(ApplyMethod(prva_stevika.set_color,YELLOW),ApplyMethod(tretja_stevilka.set_color,YELLOW))
        self.wait(0.5)
        prvi_dve = VGroup(prva_stevika, tretja_stevilka)
        drugi_dve = VGroup(druga_stevilka, cetrta_stevilka)
        self.play(TransformFromCopy(prvi_dve, enacba_3_1))
        self.wait(1)
        self.play(ApplyMethod(prvi_dve.set_color, WHITE), ApplyMethod(enacba_3_1.set_color, WHITE),ApplyMethod(drugi_dve.set_color, YELLOW))
        self.wait(1)
        druga_vsota = VGroup(enacba_3_2,enacba_3_3)
        self.play(TransformFromCopy(drugi_dve, druga_vsota))
        self.wait(1)
        self.play(ApplyMethod(drugi_dve.set_color, WHITE), FadeInFromDown(enacba_3_4),FadeInFromDown(enacba_3_5), ApplyMethod(enacba_3_3.set_color, WHITE))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        splosni_skalarni = TexMobject("\\vec{a}"," \\cdot ","\\vec{b} ","= (","a_1",",","a_2",")\\cdot(","b_1",",","b_2",") = ","a_1","b_1", " + ","a_2","b_2").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("b_1", RED).set_color_by_tex("b_2", BLUE)
        self.play(FadeInFromDown(splosni_skalarni))
        self.wait(2)
        splosni_skalarni3 = TexMobject("\\vec{a}"," \\cdot ","\\vec{b} ","= (","a_1",",","a_2",",","a_3",")\\cdot(","b_1",",","b_2",",","b_3",") = ","a_1","b_1"," + ","a_2","b_2","+","a_3","b_3").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("b_1", RED).set_color_by_tex("b_2", BLUE).set_color_by_tex("b_3", GREEN).set_color_by_tex("a_3", GREEN)
        self.play(ApplyMethod(splosni_skalarni.shift,2*UP), FadeInFromDown(splosni_skalarni3))
        self.wait(2)
        splosni_skalarnin = TexMobject("\\vec{a}"," \\cdot ","\\vec{b} ","= (","a_1",",","\\ldots",",","a_n",")\\cdot(","b_1",",","\\ldots",",","b_n",") = ","a_1","b_1"," + ","\\ldots","+","a_n","b_n").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", BLUE).set_color_by_tex("a_n", GREEN).set_color_by_tex("b_1", RED).set_color_by_tex("b_2", BLUE).set_color_by_tex("b_n", GREEN).shift(2*DOWN).set_color_by_tex("\\ldots", BLUE)
        self.play(FadeInFromDown(splosni_skalarnin))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        uporaba1 = TextMobject("Uporaba: računanje vmesnega kota").move_to(3*UP)
        vodoravnica = Line(start=3*UP + 0.5*DOWN + 4*LEFT, end = 3*UP - 4*LEFT + 0.5*DOWN)
        self.play(FadeInFromDown(uporaba1), FadeInFromDown(vodoravnica))
        self.wait(1)
        splosna_enacba_kot = TexMobject("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(1*UP)
        self.play(FadeInFromDown(splosna_enacba_kot))
        self.wait(1)
        sp12 = TexMobject("\\cos{\\varphi} =")
        sp22 = TexMobject("\\vec{a}","\\cdot","\\vec{b}"," \\over"," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        splosna_enacba_kot2 = VGroup(sp12, sp22).arrange_submobjects(RIGHT).move_to(DOWN)
        self.play(FadeInFromDown(splosna_enacba_kot2))
        self.wait(1)
        #splosna_enacba_kot3 = TexMobject("\\varphi = \\arccos{\\frac{\\vec{a}","\\cdot","\\vec{b}}{\\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert}}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(4*LEFT + 1.5*UP)
        #self.play(FadeInFromDown(splosna_enacba_kot3))
        self.wait(2)
        sp13 = TexMobject("\\cos{\\varphi} =")
        sp23 = TexMobject("a_1","b_1","+","a_2","b_2"," \\over"," \\sqrt{{a_1}^2 + {a_2}^2}","\\sqrt{{b_1}^2 + {b_2}^2}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).set_color_by_tex("a_1", RED).set_color_by_tex("a_2", RED).set_color_by_tex("b_1", BLUE).set_color_by_tex("b_2", BLUE)
        splosna_enacba_kot3 = VGroup(sp13, sp23).arrange_submobjects(RIGHT).move_to(DOWN)
        self.play(Transform(splosna_enacba_kot2,splosna_enacba_kot3), run_time=0.7)
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        #nekaj malega za predstavo (največji, najmanjši skal. produkt, pravi kot) (opravljeno)
        #zdaj sledi računanje skalarnega produkta s koordinatami vektorjev (opravljeno)
        #uporaba: računanje kota med vektorjema (opravljeno)
        #uporaba: računanje dolžine vektorja (opravljeno)
        
        uporaba2 = TextMobject("Uporaba: računanje dolžine vektorja").move_to(3*UP)
        vodoravnica2 = Line(start=3*UP + 0.5*DOWN + 4*LEFT, end = 3*UP - 4*LEFT + 0.5*DOWN)
        self.play(FadeInFromDown(uporaba2), FadeInFromDown(vodoravnica2))
        splosna_enacba_kot = TexMobject("\\vec{a}","\\cdot","\\vec{b}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(1.5*UP)
        self.play(FadeInFromDown(splosna_enacba_kot))
        self.wait(2)
        splosna_enacba_kot2 = TexMobject("\\vec{a}","\\cdot","\\vec{a}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{a} \\rvert","\\cos{\\varphi}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED)
        self.play(FadeInFromDown(splosna_enacba_kot2))
        self.wait(2)
        splosna_enacba_kot3 = TexMobject("\\vec{a}","\\cdot","\\vec{a}","="," \\lvert \\vec{a} \\rvert","\\lvert \\vec{a} \\rvert").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(0.6*LEFT)
        self.play(Transform(splosna_enacba_kot2,splosna_enacba_kot3))
        self.wait(2)
        splosna_enacba_kot4 = TexMobject("\\vec{a}","\\cdot","\\vec{a}","="," {\\lvert \\vec{a} \\rvert}^2").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(0.75*LEFT + 0.05*UP)
        self.play(Transform(splosna_enacba_kot2,splosna_enacba_kot4))
        self.wait(2)
        splosna_enacba_kot5 = TexMobject(" \\lvert \\vec{a} \\rvert","=","\\sqrt{\\vec{a} \\cdot \\vec{a}}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(1.5*DOWN +0.25*LEFT)
        self.play(FadeInFromDown(splosna_enacba_kot5))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        self.play(FadeInFromDown(splosna_enacba_kot5.shift(3*UP).shift(0.5*UP)))
        self.wait(2)
        splosna_enacba_kot6 = TexMobject("\\lvert"," \\vec{a}"," -2","\\vec{b}","\\rvert","=","\\sqrt{("," \\vec{a}"," -2","\\vec{b}",")","\\cdot","("," \\vec{a}"," -2","\\vec{b}",")}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(0.5*UP).shift(0.5*UP)
        self.play(FadeInFromDown(splosna_enacba_kot6))
        self.wait(2)
        splosna_enacba_kot7 = TexMobject("\\lvert"," \\vec{a}"," -2","\\vec{b}","\\rvert","=","\\sqrt{("," \\vec{a}","\\cdot","\\vec{a}","-4","\\vec{a}","\\cdot","\\vec{b}","+","4","\\vec{b}","\\cdot","\\vec{b}",")}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(-1*UP).shift(0.5*UP)
        self.play(FadeInFromDown(splosna_enacba_kot7))
        self.wait(2)
        splosna_enacba_kot8 = TexMobject("\\lvert"," \\vec{a}"," -2","\\vec{b}","\\rvert","=","\\sqrt{(","{\\lvert \\vec{a} \\rvert}^2","-4","\\lvert \\vec{a} \\rvert","\\lvert \\vec{b} \\rvert","\\cos{\\varphi}","+","4","{\\lvert \\vec{b} \\rvert}^2",")}").set_color_by_tex("{b}",BLUE).set_color_by_tex("{a}",RED).move_to(-2.5*UP).shift(0.5*UP)
        self.play(FadeInFromDown(splosna_enacba_kot8))
        self.wait(1)
        okvir_skal3 = SurroundingRectangle(splosna_enacba_kot8).set_color(YELLOW)
        self.play(ShowCreation(okvir_skal3))
        self.wait(2)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
class VektorskiProdukt(SpecialThreeDScene):
    def construct(self):
        
        plane = NumberPlane()
        #self.add(plane)
        vektorski_produkt = TextMobject("Vektorski produkt").scale(2.5)
        self.play(FadeIn(vektorski_produkt))
        self.wait(2)
        self.play(FadeOut(vektorski_produkt))
        
        enacba_vek_1 = TexMobject("\\vec{vektor}","\\times","\\vec{vektor}").shift(1*LEFT)
        enacba_vek_2 = TexMobject("= \\vec{vektor}").next_to(enacba_vek_1, RIGHT)
        self.play(FadeInFromDown(enacba_vek_1))
        self.wait(1)
        self.play(FadeInFromDown(enacba_vek_2))
        self.wait(1)
        self.play(ApplyMethod(enacba_vek_1.set_color_by_tex, "\\times", RED))
        self.wait(1)
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        vek_rdeci = Line(start=ORIGIN, end = math.sin(math.pi/3)*LEFT + math.cos(math.pi/3)*DOWN).set_color(RED)
        vek_modri = Line(start=ORIGIN, end = 2*math.sin(math.pi/3)*RIGHT + 2*math.cos(math.pi/3)*DOWN).set_color(BLUE)
        rdeci_trikotnik = Polygon(ORIGIN, 1*RIGHT + 1*DOWN, 1.2*LEFT + 1.5*DOWN).set_color(RED).set_fill(RED, opacity=1).scale(0.2).move_to(vek_rdeci.get_end())
        modri_trikotnik = Polygon(ORIGIN, -1*RIGHT + 1*DOWN, -1.2*LEFT + 1.5*DOWN).set_color(BLUE).set_fill(BLUE, opacity=1).scale(0.2).move_to(vek_modri.get_end())
        crka_rdeca = TexMobject("\\vec{a}").set_color(RED).move_to(0.8*LEFT + 0.2*UP)
        crka_modra = TexMobject("\\vec{b}").set_color(BLUE).move_to(1.75*RIGHT + 0.4*DOWN)
        self.play(ShowCreation(vek_rdeci), ShowCreation(vek_modri),ShowCreation(rdeci_trikotnik),ShowCreation(modri_trikotnik), Write(crka_rdeca),Write(crka_modra))
        self.wait(1)
        vek_produkt = Line(start=ORIGIN, end = 2.5*UP).set_color(PURPLE).add_tip()
        crka_produkt = TexMobject("\\vec{a}"," \\times"," \\vec{b}").move_to(vek_produkt.get_center() + 1*RIGHT).set_color(PURPLE)
        self.play(ShowCreation(vek_produkt), Write(crka_produkt))
        self.wait(1)
        crta_pravi1_1 = Line(start=0.2*UP, end = 0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT)
        crta_pravi1_2 = Line(0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT, end =0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT + 0.2*DOWN)
        pravi1 = VGroup(crta_pravi1_1, crta_pravi1_2)
        crta_pravi2_1 = Line(start=0.2*UP, end = 0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT)
        crta_pravi2_2 = Line(0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT, end =0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT + 0.2*DOWN)
        pravi2 = VGroup(crta_pravi2_1, crta_pravi2_2)
        self.play(ShowCreation(pravi1))
        self.play(ShowCreation(pravi2))
        self.wait(1)
        crtkasta_leva = DashedLine(start=1.2*LEFT +0.7*DOWN, end = 1.2*LEFT +0.7*DOWN + 2.4*(((math.sqrt(3)/2)*RIGHT) + (1/2)*DOWN))
        crtkasta_desna = DashedLine(start=2*RIGHT + 1.2*DOWN, end = 2*RIGHT + 1.2*DOWN + 1.38*(((math.sqrt(3)/2)*LEFT) + (1/2)*DOWN))
        self.play(ShowCreation(crtkasta_leva), ShowCreation(crtkasta_desna))
        self.wait(1)
        ploscina_paralelograma = Polygon(1.2*LEFT +0.7*DOWN, ORIGIN, 2*RIGHT + 1.2*DOWN, 2*RIGHT + 1.2*DOWN + 1.38*(((math.sqrt(3)/2)*LEFT) + (1/2)*DOWN) + 0.005*UP + 0.03*RIGHT).set_fill(PURPLE, opacity = 0.5)
        self.play(ShowCreation(ploscina_paralelograma))
        ploscina = TexMobject("S").set_color("#FFFF66").shift(1.1*DOWN + 0.5*RIGHT).scale(0.8)
        self.wait(1)
        self.play(Write(ploscina))
        self.wait(1)
        enacba_vek_prod = TexMobject("\\lvert","\\vec{a}"," \\times"," \\vec{b}","\\lvert"," = ","S").set_color(PURPLE).set_color_by_tex("S", "#FFFF66").set_color_by_tex("=", WHITE).move_to(4.5*LEFT + UP)
        self.wait(1)
        crka_s_in_zapis = VGroup(ploscina, crka_produkt)
        self.play(TransformFromCopy(crka_s_in_zapis, enacba_vek_prod))
        self.wait(1)
        crka_fi = TexMobject("\\varphi").shift(0.3*DOWN).scale(0.8)
        self.play(FadeInFromDown(crka_fi), FadeOut(ploscina))
        self.wait(1)
        enacba2 = TexMobject("\\lvert","\\vec{a}"," \\times"," \\vec{b}","\\lvert"," = ","\\lvert \\vec{a} \\rvert", "\\lvert \\vec{b} \\rvert","\\sin{\\varphi}").move_to(4.5*LEFT).set_color_by_tex("\\times",PURPLE).set_color_by_tex("\\rvert",PURPLE).set_color_by_tex("\\lvert",PURPLE).set_color_by_tex("\\vec{a}",PURPLE).set_color_by_tex("\\vec{b}",PURPLE).set_color_by_tex("\\lvert \\vec{a} \\rvert", RED).set_color_by_tex("\\lvert \\vec{b} \\rvert", BLUE)
        self.play(FadeInFromDown(enacba2))
        self.wait(2)
        roka =  ImageMobject("C:\\Users\\jasak\\manim\\manimlib\\mobject\\svg\\Right_hand_rule.svg.png").shift(4*RIGHT).scale(1.5)
        self.play(FadeIn(roka))
        self.wait(1)
        rdeci_arrow = Line(start = 4.6*RIGHT + 0.4*DOWN, end = 2.8*RIGHT +0.05*UP).set_color(RED).add_tip()
        modri_arrow = Line(start = 4.6*RIGHT + 0.4*DOWN, end = 3*RIGHT + 1*DOWN).set_color(BLUE).add_tip()
        crka_rdeci = TexMobject("\\vec{a}").set_color(RED).move_to(3.75*RIGHT + 0.25*UP)
        crka_modri = TexMobject("\\vec{b}").set_color(BLUE).move_to(3.75*RIGHT + 1.25*DOWN)
        crka_vijolicni = TexMobject("\\vec{a}"," \\times"," \\vec{b}").set_color(PURPLE).move_to(5.5*RIGHT + 1*UP)
        self.play(ShowCreation(rdeci_arrow),ShowCreation(modri_arrow), Write(crka_rdeci),Write(crka_modri))
        self.wait(1)
        vijolicni_arrow = Line(start = 4.6*RIGHT + 0.4*DOWN, end = 4.6*RIGHT + 0.4*DOWN + 2.25*UP).add_tip().set_color(PURPLE)
        self.play(ShowCreation(vijolicni_arrow), Write(crka_vijolicni))
        self.wait(1)
        self.play(FadeOut(ploscina_paralelograma),FadeOut(crka_fi), FadeOut(crtkasta_leva), FadeOut(crtkasta_desna))
        self.wait(1)
        vek_rdeci2 = Line(start=ORIGIN, end = -math.sin(math.pi/3)*LEFT + math.cos(math.pi/3)*DOWN).set_color(RED)
        vek_modri2 = Line(start=ORIGIN, end = -2*math.sin(math.pi/3)*RIGHT + 2*math.cos(math.pi/3)*DOWN).set_color(BLUE)
        rdeci_trikotnik2 = Polygon(ORIGIN, -1*RIGHT + 1*DOWN, -1.2*LEFT + 1.5*DOWN).set_color(RED).set_fill(RED, opacity=1).scale(0.2).move_to(-(vek_rdeci.get_end()) + 2*math.cos(math.pi/3)*DOWN)
        modri_trikotnik2 = Polygon(ORIGIN, 1*RIGHT + 1*DOWN, 1.2*LEFT + 1.5*DOWN).set_color(BLUE).set_fill(BLUE, opacity=1).scale(0.2).move_to(-(vek_modri.get_end()) + 2*2*math.cos(math.pi/3)*DOWN)
        crka_rdeca2 = TexMobject("\\vec{a}").set_color(RED).move_to(-0.8*LEFT + 0.2*UP)
        crka_modra2 = TexMobject("\\vec{b}").set_color(BLUE).move_to(-1.75*RIGHT + 0.4*DOWN)
        self.play(Transform(vek_rdeci, vek_rdeci2), Transform(vek_modri, vek_modri2), Transform(rdeci_trikotnik, rdeci_trikotnik2), Transform(modri_trikotnik, modri_trikotnik2), Transform(crka_rdeca, crka_rdeca2), Transform(crka_modra, crka_modra2))
        self.wait(1)
        vek_produkt2 = Line(start=ORIGIN, end = -2.5*UP).set_color(PURPLE).add_tip()
        crka_produkt2 = TexMobject("\\vec{b}"," \\times"," \\vec{a}").move_to(vek_produkt.get_center() + 1*RIGHT).set_color(PURPLE)
        crka_produkt3 = TexMobject("\\vec{a}"," \\times"," \\vec{b}").move_to(-(vek_produkt.get_center()) + 1*RIGHT).set_color(PURPLE)
        vek_produkt3 = Line(start=ORIGIN, end = 2.5*UP).set_color(PURPLE).add_tip()
        crta_pravi1_12 = Line(start=-0.2*UP, end = -0.2*(1/2)*UP + -0.2*UP + (0.2*math.sqrt(3)/2)*RIGHT)
        crta_pravi1_22 = Line(start=-0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT, end =-0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT + 0.2*DOWN)
        pravi12 = VGroup(crta_pravi1_12, crta_pravi1_22)
        crta_pravi2_12 = Line(start=-0.2*UP, end = -0.2*UP -0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT)
        crta_pravi2_22 = Line(-0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT, end =-0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT + 0.2*DOWN)
        pravi22 = VGroup(crta_pravi2_12, crta_pravi2_22)
        crta_pravi1_13 = Line(start=0.2*UP, end = 0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT)
        crta_pravi1_23 = Line(0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT, end =0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*RIGHT + 0.2*DOWN)
        pravi13 = VGroup(crta_pravi1_13, crta_pravi1_23)
        crta_pravi2_13 = Line(start=0.2*UP, end = 0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT)
        crta_pravi2_23 = Line(0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT, end =0.2*(1/2)*UP + (0.2*math.sqrt(3)/2)*LEFT + 0.2*DOWN)
        pravi23 = VGroup(crta_pravi2_13, crta_pravi2_23)
        self.play(Transform(vek_produkt, vek_produkt2), Transform(crka_produkt, crka_produkt3), Transform(pravi1, pravi12), Transform(pravi2, pravi22))
        self.wait(2)
        
        self.play(Transform(crka_produkt, crka_produkt2), Transform(vek_produkt, vek_produkt3),Transform(pravi1, pravi13),Transform(pravi2, pravi23))
        self.wait(1)
        self.wait(1)
        
        #jutri - primitivna shema (tako kot pri skalarnem produktu) (opravljeno)
        #pravilo desne roke - tudi pokazati, kaj se zgodi, če sta vektorja zamenjana (opravljeno)
        #kako se izračuna vektorski produkt s koordinatami 3d vektorjev (determinante) (opravljeno)
        
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        
        enacba_vek_prikaz1 = TexMobject("\\vec{a}"," \\times ","\\vec{b}"," \\neq ","\\vec{b}"," \\times ","\\vec{a}").set_color_by_tex("a", RED).set_color_by_tex("b", BLUE).shift(UP)
        enacba_vek_prikaz2 = TexMobject("\\vec{a}"," \\times ","\\vec{b}"," =","-","\\vec{b}"," \\times ","\\vec{a}").set_color_by_tex("a", RED).set_color_by_tex("b", BLUE).shift(DOWN)
        self.play(FadeIn(enacba_vek_prikaz1))
        self.wait(1)
        self.play(FadeIn(enacba_vek_prikaz2))
        self.wait(1)
        
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )
        #.set_color_by_tex("a", RED).set_color_by_tex("b", BLUE)
        #self.add(plane)
        v_vek_1 = TexMobject("\\vec{a}"," = (","a_1",", ","a_2",", ","a_3",")").set_color_by_tex("a", RED).move_to(2.5*UP + 2.5*LEFT)
        v_vek_2 = TexMobject("\\vec{b}"," = (","b_1",", ","b_2",", ","b_3",")").set_color_by_tex("b", BLUE).move_to(2.5*UP + 2.5*RIGHT)
        
        matrika_00 = TexMobject("\\vec{i}").shift(0.5*LEFT)
        matrika_01 = TexMobject("\\vec{j}")
        matrika_02 = TexMobject("\\vec{k}").shift(0.3*RIGHT)
        matrika_10 = TexMobject("a_1").set_color(RED).shift(0.5*LEFT)
        matrika_11 = TexMobject("a_2").set_color(RED)
        matrika_12 = TexMobject("a_3").set_color(RED).shift(0.3*RIGHT)
        matrika_20 = TexMobject("b_1").set_color(BLUE).shift(0.5*LEFT)
        matrika_21 = TexMobject("b_2").set_color(BLUE)
        matrika_22 = TexMobject("b_3").set_color(BLUE).shift(0.3*RIGHT)
        
        zgornji_stolpec = VGroup(matrika_00, matrika_01, matrika_02).arrange_submobjects(RIGHT)
        srednji_stolpec = VGroup(matrika_10, matrika_11, matrika_12).arrange_submobjects(RIGHT)
        spodnji_stolpec = VGroup(matrika_20, matrika_21, matrika_22).arrange_submobjects(RIGHT)
        crta1 = Line(start = 1.5*LEFT + UP, end = 1.5*LEFT + 1.125*DOWN)
        crta2 = Line(start = -1.5*LEFT + UP, end = -1.5*LEFT + 1.125*DOWN)
        matrika_zac = VGroup(zgornji_stolpec, srednji_stolpec, spodnji_stolpec).arrange_submobjects(DOWN)
        matrika = VGroup(crta1, matrika_zac, crta2)
        
        matrika_00.shift(0.5*LEFT).shift(0.3*UP)
        matrika_01.shift(0.3*UP)
        matrika_02.shift(0.5*RIGHT).shift(0.3*UP)
        matrika_10.shift(0.4*LEFT)
        matrika_11.set_color(RED)
        matrika_12.shift(0.4*RIGHT)
        matrika_20.shift(0.4*LEFT).shift(-0.3*UP)
        matrika_21.set_color(BLUE).shift(-0.3*UP)
        matrika_22.set_color(BLUE).shift(0.4*RIGHT).shift(-0.3*UP)
        
        self.play(FadeInFromDown(v_vek_1))
        self.play(FadeInFromDown(v_vek_2))
        self.wait(1)
        self.play(FadeIn(matrika))
        self.wait(1)
        self.play(ApplyMethod(matrika.shift, 4*LEFT))
        self.wait(1)
        enacaj = TexMobject("=").shift(2*LEFT)
        self.play(Write(enacaj))
        
        determinanta_i = TexMobject(
   "\\begin{vmatrix}" 
   "a_{2} & a_{3}  \\\\"
   "b_{2} & b_{3}  \\\\"
   "\\end{vmatrix} \\vec{i}"
            )
        determinanta_j = TexMobject(
   "-\\begin{vmatrix}" 
   "a_{1} & a_{3}  \\\\"
   "b_{1} & b_{3}  \\\\"
   "\\end{vmatrix} \\vec{j}"
            )
        determinanta_k = TexMobject(
   "+\\begin{vmatrix}" 
   "a_{1} & a_{2}  \\\\"
   "b_{1} & b_{2}  \\\\"
   "\\end{vmatrix} \\vec{k}"
            )
        determinanta_i[0][4].set_color(RED)
        determinanta_i[0][5].set_color(RED)
        determinanta_i[0][6].set_color(RED)
        determinanta_i[0][7].set_color(RED)
        determinanta_i[0][8].set_color(BLUE)
        determinanta_i[0][9].set_color(BLUE)
        determinanta_i[0][10].set_color(BLUE)
        determinanta_i[0][11].set_color(BLUE)
        
        determinanta_j[0][0].set_color(YELLOW)
        determinanta_j[0][5].set_color(RED)
        determinanta_j[0][6].set_color(RED)
        determinanta_j[0][7].set_color(RED)
        determinanta_j[0][8].set_color(RED)
        determinanta_j[0][9].set_color(BLUE)
        determinanta_j[0][10].set_color(BLUE)
        determinanta_j[0][11].set_color(BLUE)
        determinanta_j[0][12].set_color(BLUE)
        
        determinanta_k[0][0].set_color(YELLOW)
        determinanta_k[0][5].set_color(RED)
        determinanta_k[0][6].set_color(RED)
        determinanta_k[0][7].set_color(RED)
        determinanta_k[0][8].set_color(RED)
        determinanta_k[0][9].set_color(BLUE)
        determinanta_k[0][10].set_color(BLUE)
        determinanta_k[0][11].set_color(BLUE)
        determinanta_k[0][12].set_color(BLUE)
        
        determinanta_i.shift(0.5*LEFT)
        determinanta_j.shift(2*RIGHT)
        determinanta_k.shift(4.8*RIGHT)
        
        krog_i = SurroundingRectangle(matrika_00).set_color(YELLOW)
        kvadrat_i = SurroundingRectangle(VGroup(matrika_11, matrika_12, matrika_21, matrika_22)).set_color(YELLOW)
        self.play(ShowCreation(krog_i),ShowCreation(kvadrat_i))
        self.wait(2)
        self.play(FadeInFromDown(determinanta_i))
        self.wait(2)
        krog_j = SurroundingRectangle(matrika_01).set_color(YELLOW)
        kvadrat_j1 = SurroundingRectangle(VGroup(matrika_10, matrika_20)).set_color(YELLOW)
        kvadrat_j2 = SurroundingRectangle(VGroup(matrika_12, matrika_22)).set_color(YELLOW)
        kvadrat_j = VGroup(kvadrat_j1, kvadrat_j2)
        self.play(Transform(krog_i,krog_j),Transform(kvadrat_i,kvadrat_j))
        self.wait(1)
        self.play(FadeInFromDown(determinanta_j))
        self.wait(1)
        krog_k = SurroundingRectangle(matrika_02).set_color(YELLOW)
        kvadrat_k = SurroundingRectangle(VGroup(matrika_11, matrika_10, matrika_21, matrika_20)).set_color(YELLOW)
        self.play(Transform(krog_i,krog_k),Transform(kvadrat_i,kvadrat_k))
        self.wait(1)
        self.play(FadeInFromDown(determinanta_k))
        self.wait(1)
        self.play(FadeOut(kvadrat_i), FadeOut(krog_i))
        self.wait(1)
        zadnja_enacba = TexMobject("\\vec{a}"," \\times"," \\vec{b} ","= (","a_2","b_3"," - ","a_3","b_2",", ","a_3","b_1"," - ","a_1","b_3",", ","a_1","b_2"," - ","a_2","b_1",")").set_color_by_tex("a", RED).set_color_by_tex("b", BLUE)
        zadnja_enacba.shift(2*DOWN + 1.5*RIGHT)
        self.play(FadeInFromDown(zadnja_enacba))
        self.wait(1)
        
        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )

class Primer(Scene):
    #ta class je samo zato, če je treba kaj eksperimentirati
    def construct(self):
        """
        kvadrat = Square().set_color(RED)
        krog = Circle().set_color(BLUE).set_fill(ORANGE, opacity=0.5)
        self.play(ShowCreation(kvadrat))
        self.wait(1)
        self.play(Transform(kvadrat, krog))
        
        enacba = TexMobject("\\int{e^x \\, dx} = e^x + c")
        self.play(FadeOut(kvadrat))
        self.play(Write(enacba))
        self.play(ApplyMethod(enacba.shift, 1.8*UP))
        enacba2 = TexMobject("\\int{\\frac{1}{1 + x^2} \\, dx} = \\arctan{x} + c")
        self.play(Write(enacba2))
        """
        plane = NumberPlane()
        self.play(ShowCreation(plane))
        self.wait(10)
        
